run:
  tests: true
  skip-dirs:
    - _examples

linters:
  enable:
    - govet
    - goconst
    - forbidigo
    - errcheck

linters-settings:
  govet:
    check-shadowing: true
  goconst:
    min-len: 8
    min-occurrences: 3
  forbidigo:
    #forbid:
    #  - (Must)?NewLexer$
    exclude_godoc_examples: false

issues:
  exclude:
    - 'struct literal uses unkeyed fields'
    - 'declaration of "err" shadows declaration'
