// Code generated by "enumer -text -type TokenType"; DO NOT EDIT.

package chroma

import (
	"fmt"
	"strings"
)

const _TokenTypeName = "IgnoreNoneOtherErrorCodeLineLineLinkLineTableTDLineTableLineHighlightLineNumbersTableLineNumbersLinePreWrapperBackgroundKeywordKeywordConstantKeywordDeclarationKeywordNamespaceKeywordPseudoKeywordReservedKeywordTypeNameNameAttributeNameClassNameConstantNameDecoratorNameEntityNameExceptionNameKeywordNameLabelNameNamespaceNameOperatorNameOtherNamePseudoNamePropertyNameTagNameBuiltinNameBuiltinPseudoNameVariableNameVariableAnonymousNameVariableClassNameVariableGlobalNameVariableInstanceNameVariableMagicNameFunctionNameFunctionMagicLiteralLiteralDateLiteralOtherLiteralStringLiteralStringAffixLiteralStringAtomLiteralStringBacktickLiteralStringBooleanLiteralStringCharLiteralStringDelimiterLiteralStringDocLiteralStringDoubleLiteralStringEscapeLiteralStringHeredocLiteralStringInterpolLiteralStringNameLiteralStringOtherLiteralStringRegexLiteralStringSingleLiteralStringSymbolLiteralNumberLiteralNumberBinLiteralNumberFloatLiteralNumberHexLiteralNumberIntegerLiteralNumberIntegerLongLiteralNumberOctLiteralNumberByteOperatorOperatorWordOperatorReservedPunctuationCommentCommentHashbangCommentMultilineCommentSingleCommentSpecialCommentPreprocCommentPreprocFileGenericGenericDeletedGenericEmphGenericErrorGenericHeadingGenericInsertedGenericOutputGenericPromptGenericStrongGenericSubheadingGenericTracebackGenericUnderlineTextTextWhitespaceTextSymbolTextPunctuation"
const _TokenTypeLowerName = "ignorenoneothererrorcodelinelinelinklinetabletdlinetablelinehighlightlinenumberstablelinenumberslineprewrapperbackgroundkeywordkeywordconstantkeyworddeclarationkeywordnamespacekeywordpseudokeywordreservedkeywordtypenamenameattributenameclassnameconstantnamedecoratornameentitynameexceptionnamekeywordnamelabelnamenamespacenameoperatornameothernamepseudonamepropertynametagnamebuiltinnamebuiltinpseudonamevariablenamevariableanonymousnamevariableclassnamevariableglobalnamevariableinstancenamevariablemagicnamefunctionnamefunctionmagicliteralliteraldateliteralotherliteralstringliteralstringaffixliteralstringatomliteralstringbacktickliteralstringbooleanliteralstringcharliteralstringdelimiterliteralstringdocliteralstringdoubleliteralstringescapeliteralstringheredocliteralstringinterpolliteralstringnameliteralstringotherliteralstringregexliteralstringsingleliteralstringsymbolliteralnumberliteralnumberbinliteralnumberfloatliteralnumberhexliteralnumberintegerliteralnumberintegerlongliteralnumberoctliteralnumberbyteoperatoroperatorwordoperatorreservedpunctuationcommentcommenthashbangcommentmultilinecommentsinglecommentspecialcommentpreproccommentpreprocfilegenericgenericdeletedgenericemphgenericerrorgenericheadinggenericinsertedgenericoutputgenericpromptgenericstronggenericsubheadinggenerictracebackgenericunderlinetexttextwhitespacetextsymboltextpunctuation"

var _TokenTypeMap = map[TokenType]string{
	-14:  _TokenTypeName[0:6],
	-13:  _TokenTypeName[6:10],
	-12:  _TokenTypeName[10:15],
	-11:  _TokenTypeName[15:20],
	-10:  _TokenTypeName[20:28],
	-9:   _TokenTypeName[28:36],
	-8:   _TokenTypeName[36:47],
	-7:   _TokenTypeName[47:56],
	-6:   _TokenTypeName[56:69],
	-5:   _TokenTypeName[69:85],
	-4:   _TokenTypeName[85:96],
	-3:   _TokenTypeName[96:100],
	-2:   _TokenTypeName[100:110],
	-1:   _TokenTypeName[110:120],
	1000: _TokenTypeName[120:127],
	1001: _TokenTypeName[127:142],
	1002: _TokenTypeName[142:160],
	1003: _TokenTypeName[160:176],
	1004: _TokenTypeName[176:189],
	1005: _TokenTypeName[189:204],
	1006: _TokenTypeName[204:215],
	2000: _TokenTypeName[215:219],
	2001: _TokenTypeName[219:232],
	2002: _TokenTypeName[232:241],
	2003: _TokenTypeName[241:253],
	2004: _TokenTypeName[253:266],
	2005: _TokenTypeName[266:276],
	2006: _TokenTypeName[276:289],
	2007: _TokenTypeName[289:300],
	2008: _TokenTypeName[300:309],
	2009: _TokenTypeName[309:322],
	2010: _TokenTypeName[322:334],
	2011: _TokenTypeName[334:343],
	2012: _TokenTypeName[343:353],
	2013: _TokenTypeName[353:365],
	2014: _TokenTypeName[365:372],
	2100: _TokenTypeName[372:383],
	2101: _TokenTypeName[383:400],
	2200: _TokenTypeName[400:412],
	2201: _TokenTypeName[412:433],
	2202: _TokenTypeName[433:450],
	2203: _TokenTypeName[450:468],
	2204: _TokenTypeName[468:488],
	2205: _TokenTypeName[488:505],
	2300: _TokenTypeName[505:517],
	2301: _TokenTypeName[517:534],
	3000: _TokenTypeName[534:541],
	3001: _TokenTypeName[541:552],
	3002: _TokenTypeName[552:564],
	3100: _TokenTypeName[564:577],
	3101: _TokenTypeName[577:595],
	3102: _TokenTypeName[595:612],
	3103: _TokenTypeName[612:633],
	3104: _TokenTypeName[633:653],
	3105: _TokenTypeName[653:670],
	3106: _TokenTypeName[670:692],
	3107: _TokenTypeName[692:708],
	3108: _TokenTypeName[708:727],
	3109: _TokenTypeName[727:746],
	3110: _TokenTypeName[746:766],
	3111: _TokenTypeName[766:787],
	3112: _TokenTypeName[787:804],
	3113: _TokenTypeName[804:822],
	3114: _TokenTypeName[822:840],
	3115: _TokenTypeName[840:859],
	3116: _TokenTypeName[859:878],
	3200: _TokenTypeName[878:891],
	3201: _TokenTypeName[891:907],
	3202: _TokenTypeName[907:925],
	3203: _TokenTypeName[925:941],
	3204: _TokenTypeName[941:961],
	3205: _TokenTypeName[961:985],
	3206: _TokenTypeName[985:1001],
	3207: _TokenTypeName[1001:1018],
	4000: _TokenTypeName[1018:1026],
	4001: _TokenTypeName[1026:1038],
	4002: _TokenTypeName[1038:1054],
	5000: _TokenTypeName[1054:1065],
	6000: _TokenTypeName[1065:1072],
	6001: _TokenTypeName[1072:1087],
	6002: _TokenTypeName[1087:1103],
	6003: _TokenTypeName[1103:1116],
	6004: _TokenTypeName[1116:1130],
	6100: _TokenTypeName[1130:1144],
	6101: _TokenTypeName[1144:1162],
	7000: _TokenTypeName[1162:1169],
	7001: _TokenTypeName[1169:1183],
	7002: _TokenTypeName[1183:1194],
	7003: _TokenTypeName[1194:1206],
	7004: _TokenTypeName[1206:1220],
	7005: _TokenTypeName[1220:1235],
	7006: _TokenTypeName[1235:1248],
	7007: _TokenTypeName[1248:1261],
	7008: _TokenTypeName[1261:1274],
	7009: _TokenTypeName[1274:1291],
	7010: _TokenTypeName[1291:1307],
	7011: _TokenTypeName[1307:1323],
	8000: _TokenTypeName[1323:1327],
	8001: _TokenTypeName[1327:1341],
	8002: _TokenTypeName[1341:1351],
	8003: _TokenTypeName[1351:1366],
}

func (i TokenType) String() string {
	if str, ok := _TokenTypeMap[i]; ok {
		return str
	}
	return fmt.Sprintf("TokenType(%d)", i)
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TokenTypeNoOp() {
	var x [1]struct{}
	_ = x[Ignore-(-14)]
	_ = x[None-(-13)]
	_ = x[Other-(-12)]
	_ = x[Error-(-11)]
	_ = x[CodeLine-(-10)]
	_ = x[LineLink-(-9)]
	_ = x[LineTableTD-(-8)]
	_ = x[LineTable-(-7)]
	_ = x[LineHighlight-(-6)]
	_ = x[LineNumbersTable-(-5)]
	_ = x[LineNumbers-(-4)]
	_ = x[Line-(-3)]
	_ = x[PreWrapper-(-2)]
	_ = x[Background-(-1)]
	_ = x[Keyword-(1000)]
	_ = x[KeywordConstant-(1001)]
	_ = x[KeywordDeclaration-(1002)]
	_ = x[KeywordNamespace-(1003)]
	_ = x[KeywordPseudo-(1004)]
	_ = x[KeywordReserved-(1005)]
	_ = x[KeywordType-(1006)]
	_ = x[Name-(2000)]
	_ = x[NameAttribute-(2001)]
	_ = x[NameClass-(2002)]
	_ = x[NameConstant-(2003)]
	_ = x[NameDecorator-(2004)]
	_ = x[NameEntity-(2005)]
	_ = x[NameException-(2006)]
	_ = x[NameKeyword-(2007)]
	_ = x[NameLabel-(2008)]
	_ = x[NameNamespace-(2009)]
	_ = x[NameOperator-(2010)]
	_ = x[NameOther-(2011)]
	_ = x[NamePseudo-(2012)]
	_ = x[NameProperty-(2013)]
	_ = x[NameTag-(2014)]
	_ = x[NameBuiltin-(2100)]
	_ = x[NameBuiltinPseudo-(2101)]
	_ = x[NameVariable-(2200)]
	_ = x[NameVariableAnonymous-(2201)]
	_ = x[NameVariableClass-(2202)]
	_ = x[NameVariableGlobal-(2203)]
	_ = x[NameVariableInstance-(2204)]
	_ = x[NameVariableMagic-(2205)]
	_ = x[NameFunction-(2300)]
	_ = x[NameFunctionMagic-(2301)]
	_ = x[Literal-(3000)]
	_ = x[LiteralDate-(3001)]
	_ = x[LiteralOther-(3002)]
	_ = x[LiteralString-(3100)]
	_ = x[LiteralStringAffix-(3101)]
	_ = x[LiteralStringAtom-(3102)]
	_ = x[LiteralStringBacktick-(3103)]
	_ = x[LiteralStringBoolean-(3104)]
	_ = x[LiteralStringChar-(3105)]
	_ = x[LiteralStringDelimiter-(3106)]
	_ = x[LiteralStringDoc-(3107)]
	_ = x[LiteralStringDouble-(3108)]
	_ = x[LiteralStringEscape-(3109)]
	_ = x[LiteralStringHeredoc-(3110)]
	_ = x[LiteralStringInterpol-(3111)]
	_ = x[LiteralStringName-(3112)]
	_ = x[LiteralStringOther-(3113)]
	_ = x[LiteralStringRegex-(3114)]
	_ = x[LiteralStringSingle-(3115)]
	_ = x[LiteralStringSymbol-(3116)]
	_ = x[LiteralNumber-(3200)]
	_ = x[LiteralNumberBin-(3201)]
	_ = x[LiteralNumberFloat-(3202)]
	_ = x[LiteralNumberHex-(3203)]
	_ = x[LiteralNumberInteger-(3204)]
	_ = x[LiteralNumberIntegerLong-(3205)]
	_ = x[LiteralNumberOct-(3206)]
	_ = x[LiteralNumberByte-(3207)]
	_ = x[Operator-(4000)]
	_ = x[OperatorWord-(4001)]
	_ = x[OperatorReserved-(4002)]
	_ = x[Punctuation-(5000)]
	_ = x[Comment-(6000)]
	_ = x[CommentHashbang-(6001)]
	_ = x[CommentMultiline-(6002)]
	_ = x[CommentSingle-(6003)]
	_ = x[CommentSpecial-(6004)]
	_ = x[CommentPreproc-(6100)]
	_ = x[CommentPreprocFile-(6101)]
	_ = x[Generic-(7000)]
	_ = x[GenericDeleted-(7001)]
	_ = x[GenericEmph-(7002)]
	_ = x[GenericError-(7003)]
	_ = x[GenericHeading-(7004)]
	_ = x[GenericInserted-(7005)]
	_ = x[GenericOutput-(7006)]
	_ = x[GenericPrompt-(7007)]
	_ = x[GenericStrong-(7008)]
	_ = x[GenericSubheading-(7009)]
	_ = x[GenericTraceback-(7010)]
	_ = x[GenericUnderline-(7011)]
	_ = x[Text-(8000)]
	_ = x[TextWhitespace-(8001)]
	_ = x[TextSymbol-(8002)]
	_ = x[TextPunctuation-(8003)]
}

var _TokenTypeValues = []TokenType{Ignore, None, Other, Error, CodeLine, LineLink, LineTableTD, LineTable, LineHighlight, LineNumbersTable, LineNumbers, Line, PreWrapper, Background, Keyword, KeywordConstant, KeywordDeclaration, KeywordNamespace, KeywordPseudo, KeywordReserved, KeywordType, Name, NameAttribute, NameClass, NameConstant, NameDecorator, NameEntity, NameException, NameKeyword, NameLabel, NameNamespace, NameOperator, NameOther, NamePseudo, NameProperty, NameTag, NameBuiltin, NameBuiltinPseudo, NameVariable, NameVariableAnonymous, NameVariableClass, NameVariableGlobal, NameVariableInstance, NameVariableMagic, NameFunction, NameFunctionMagic, Literal, LiteralDate, LiteralOther, LiteralString, LiteralStringAffix, LiteralStringAtom, LiteralStringBacktick, LiteralStringBoolean, LiteralStringChar, LiteralStringDelimiter, LiteralStringDoc, LiteralStringDouble, LiteralStringEscape, LiteralStringHeredoc, LiteralStringInterpol, LiteralStringName, LiteralStringOther, LiteralStringRegex, LiteralStringSingle, LiteralStringSymbol, LiteralNumber, LiteralNumberBin, LiteralNumberFloat, LiteralNumberHex, LiteralNumberInteger, LiteralNumberIntegerLong, LiteralNumberOct, LiteralNumberByte, Operator, OperatorWord, OperatorReserved, Punctuation, Comment, CommentHashbang, CommentMultiline, CommentSingle, CommentSpecial, CommentPreproc, CommentPreprocFile, Generic, GenericDeleted, GenericEmph, GenericError, GenericHeading, GenericInserted, GenericOutput, GenericPrompt, GenericStrong, GenericSubheading, GenericTraceback, GenericUnderline, Text, TextWhitespace, TextSymbol, TextPunctuation}

var _TokenTypeNameToValueMap = map[string]TokenType{
	_TokenTypeName[0:6]:            Ignore,
	_TokenTypeLowerName[0:6]:       Ignore,
	_TokenTypeName[6:10]:           None,
	_TokenTypeLowerName[6:10]:      None,
	_TokenTypeName[10:15]:          Other,
	_TokenTypeLowerName[10:15]:     Other,
	_TokenTypeName[15:20]:          Error,
	_TokenTypeLowerName[15:20]:     Error,
	_TokenTypeName[20:28]:          CodeLine,
	_TokenTypeLowerName[20:28]:     CodeLine,
	_TokenTypeName[28:36]:          LineLink,
	_TokenTypeLowerName[28:36]:     LineLink,
	_TokenTypeName[36:47]:          LineTableTD,
	_TokenTypeLowerName[36:47]:     LineTableTD,
	_TokenTypeName[47:56]:          LineTable,
	_TokenTypeLowerName[47:56]:     LineTable,
	_TokenTypeName[56:69]:          LineHighlight,
	_TokenTypeLowerName[56:69]:     LineHighlight,
	_TokenTypeName[69:85]:          LineNumbersTable,
	_TokenTypeLowerName[69:85]:     LineNumbersTable,
	_TokenTypeName[85:96]:          LineNumbers,
	_TokenTypeLowerName[85:96]:     LineNumbers,
	_TokenTypeName[96:100]:         Line,
	_TokenTypeLowerName[96:100]:    Line,
	_TokenTypeName[100:110]:        PreWrapper,
	_TokenTypeLowerName[100:110]:   PreWrapper,
	_TokenTypeName[110:120]:        Background,
	_TokenTypeLowerName[110:120]:   Background,
	_TokenTypeName[120:127]:        Keyword,
	_TokenTypeLowerName[120:127]:   Keyword,
	_TokenTypeName[127:142]:        KeywordConstant,
	_TokenTypeLowerName[127:142]:   KeywordConstant,
	_TokenTypeName[142:160]:        KeywordDeclaration,
	_TokenTypeLowerName[142:160]:   KeywordDeclaration,
	_TokenTypeName[160:176]:        KeywordNamespace,
	_TokenTypeLowerName[160:176]:   KeywordNamespace,
	_TokenTypeName[176:189]:        KeywordPseudo,
	_TokenTypeLowerName[176:189]:   KeywordPseudo,
	_TokenTypeName[189:204]:        KeywordReserved,
	_TokenTypeLowerName[189:204]:   KeywordReserved,
	_TokenTypeName[204:215]:        KeywordType,
	_TokenTypeLowerName[204:215]:   KeywordType,
	_TokenTypeName[215:219]:        Name,
	_TokenTypeLowerName[215:219]:   Name,
	_TokenTypeName[219:232]:        NameAttribute,
	_TokenTypeLowerName[219:232]:   NameAttribute,
	_TokenTypeName[232:241]:        NameClass,
	_TokenTypeLowerName[232:241]:   NameClass,
	_TokenTypeName[241:253]:        NameConstant,
	_TokenTypeLowerName[241:253]:   NameConstant,
	_TokenTypeName[253:266]:        NameDecorator,
	_TokenTypeLowerName[253:266]:   NameDecorator,
	_TokenTypeName[266:276]:        NameEntity,
	_TokenTypeLowerName[266:276]:   NameEntity,
	_TokenTypeName[276:289]:        NameException,
	_TokenTypeLowerName[276:289]:   NameException,
	_TokenTypeName[289:300]:        NameKeyword,
	_TokenTypeLowerName[289:300]:   NameKeyword,
	_TokenTypeName[300:309]:        NameLabel,
	_TokenTypeLowerName[300:309]:   NameLabel,
	_TokenTypeName[309:322]:        NameNamespace,
	_TokenTypeLowerName[309:322]:   NameNamespace,
	_TokenTypeName[322:334]:        NameOperator,
	_TokenTypeLowerName[322:334]:   NameOperator,
	_TokenTypeName[334:343]:        NameOther,
	_TokenTypeLowerName[334:343]:   NameOther,
	_TokenTypeName[343:353]:        NamePseudo,
	_TokenTypeLowerName[343:353]:   NamePseudo,
	_TokenTypeName[353:365]:        NameProperty,
	_TokenTypeLowerName[353:365]:   NameProperty,
	_TokenTypeName[365:372]:        NameTag,
	_TokenTypeLowerName[365:372]:   NameTag,
	_TokenTypeName[372:383]:        NameBuiltin,
	_TokenTypeLowerName[372:383]:   NameBuiltin,
	_TokenTypeName[383:400]:        NameBuiltinPseudo,
	_TokenTypeLowerName[383:400]:   NameBuiltinPseudo,
	_TokenTypeName[400:412]:        NameVariable,
	_TokenTypeLowerName[400:412]:   NameVariable,
	_TokenTypeName[412:433]:        NameVariableAnonymous,
	_TokenTypeLowerName[412:433]:   NameVariableAnonymous,
	_TokenTypeName[433:450]:        NameVariableClass,
	_TokenTypeLowerName[433:450]:   NameVariableClass,
	_TokenTypeName[450:468]:        NameVariableGlobal,
	_TokenTypeLowerName[450:468]:   NameVariableGlobal,
	_TokenTypeName[468:488]:        NameVariableInstance,
	_TokenTypeLowerName[468:488]:   NameVariableInstance,
	_TokenTypeName[488:505]:        NameVariableMagic,
	_TokenTypeLowerName[488:505]:   NameVariableMagic,
	_TokenTypeName[505:517]:        NameFunction,
	_TokenTypeLowerName[505:517]:   NameFunction,
	_TokenTypeName[517:534]:        NameFunctionMagic,
	_TokenTypeLowerName[517:534]:   NameFunctionMagic,
	_TokenTypeName[534:541]:        Literal,
	_TokenTypeLowerName[534:541]:   Literal,
	_TokenTypeName[541:552]:        LiteralDate,
	_TokenTypeLowerName[541:552]:   LiteralDate,
	_TokenTypeName[552:564]:        LiteralOther,
	_TokenTypeLowerName[552:564]:   LiteralOther,
	_TokenTypeName[564:577]:        LiteralString,
	_TokenTypeLowerName[564:577]:   LiteralString,
	_TokenTypeName[577:595]:        LiteralStringAffix,
	_TokenTypeLowerName[577:595]:   LiteralStringAffix,
	_TokenTypeName[595:612]:        LiteralStringAtom,
	_TokenTypeLowerName[595:612]:   LiteralStringAtom,
	_TokenTypeName[612:633]:        LiteralStringBacktick,
	_TokenTypeLowerName[612:633]:   LiteralStringBacktick,
	_TokenTypeName[633:653]:        LiteralStringBoolean,
	_TokenTypeLowerName[633:653]:   LiteralStringBoolean,
	_TokenTypeName[653:670]:        LiteralStringChar,
	_TokenTypeLowerName[653:670]:   LiteralStringChar,
	_TokenTypeName[670:692]:        LiteralStringDelimiter,
	_TokenTypeLowerName[670:692]:   LiteralStringDelimiter,
	_TokenTypeName[692:708]:        LiteralStringDoc,
	_TokenTypeLowerName[692:708]:   LiteralStringDoc,
	_TokenTypeName[708:727]:        LiteralStringDouble,
	_TokenTypeLowerName[708:727]:   LiteralStringDouble,
	_TokenTypeName[727:746]:        LiteralStringEscape,
	_TokenTypeLowerName[727:746]:   LiteralStringEscape,
	_TokenTypeName[746:766]:        LiteralStringHeredoc,
	_TokenTypeLowerName[746:766]:   LiteralStringHeredoc,
	_TokenTypeName[766:787]:        LiteralStringInterpol,
	_TokenTypeLowerName[766:787]:   LiteralStringInterpol,
	_TokenTypeName[787:804]:        LiteralStringName,
	_TokenTypeLowerName[787:804]:   LiteralStringName,
	_TokenTypeName[804:822]:        LiteralStringOther,
	_TokenTypeLowerName[804:822]:   LiteralStringOther,
	_TokenTypeName[822:840]:        LiteralStringRegex,
	_TokenTypeLowerName[822:840]:   LiteralStringRegex,
	_TokenTypeName[840:859]:        LiteralStringSingle,
	_TokenTypeLowerName[840:859]:   LiteralStringSingle,
	_TokenTypeName[859:878]:        LiteralStringSymbol,
	_TokenTypeLowerName[859:878]:   LiteralStringSymbol,
	_TokenTypeName[878:891]:        LiteralNumber,
	_TokenTypeLowerName[878:891]:   LiteralNumber,
	_TokenTypeName[891:907]:        LiteralNumberBin,
	_TokenTypeLowerName[891:907]:   LiteralNumberBin,
	_TokenTypeName[907:925]:        LiteralNumberFloat,
	_TokenTypeLowerName[907:925]:   LiteralNumberFloat,
	_TokenTypeName[925:941]:        LiteralNumberHex,
	_TokenTypeLowerName[925:941]:   LiteralNumberHex,
	_TokenTypeName[941:961]:        LiteralNumberInteger,
	_TokenTypeLowerName[941:961]:   LiteralNumberInteger,
	_TokenTypeName[961:985]:        LiteralNumberIntegerLong,
	_TokenTypeLowerName[961:985]:   LiteralNumberIntegerLong,
	_TokenTypeName[985:1001]:       LiteralNumberOct,
	_TokenTypeLowerName[985:1001]:  LiteralNumberOct,
	_TokenTypeName[1001:1018]:      LiteralNumberByte,
	_TokenTypeLowerName[1001:1018]: LiteralNumberByte,
	_TokenTypeName[1018:1026]:      Operator,
	_TokenTypeLowerName[1018:1026]: Operator,
	_TokenTypeName[1026:1038]:      OperatorWord,
	_TokenTypeLowerName[1026:1038]: OperatorWord,
	_TokenTypeName[1038:1054]:      OperatorReserved,
	_TokenTypeLowerName[1038:1054]: OperatorReserved,
	_TokenTypeName[1054:1065]:      Punctuation,
	_TokenTypeLowerName[1054:1065]: Punctuation,
	_TokenTypeName[1065:1072]:      Comment,
	_TokenTypeLowerName[1065:1072]: Comment,
	_TokenTypeName[1072:1087]:      CommentHashbang,
	_TokenTypeLowerName[1072:1087]: CommentHashbang,
	_TokenTypeName[1087:1103]:      CommentMultiline,
	_TokenTypeLowerName[1087:1103]: CommentMultiline,
	_TokenTypeName[1103:1116]:      CommentSingle,
	_TokenTypeLowerName[1103:1116]: CommentSingle,
	_TokenTypeName[1116:1130]:      CommentSpecial,
	_TokenTypeLowerName[1116:1130]: CommentSpecial,
	_TokenTypeName[1130:1144]:      CommentPreproc,
	_TokenTypeLowerName[1130:1144]: CommentPreproc,
	_TokenTypeName[1144:1162]:      CommentPreprocFile,
	_TokenTypeLowerName[1144:1162]: CommentPreprocFile,
	_TokenTypeName[1162:1169]:      Generic,
	_TokenTypeLowerName[1162:1169]: Generic,
	_TokenTypeName[1169:1183]:      GenericDeleted,
	_TokenTypeLowerName[1169:1183]: GenericDeleted,
	_TokenTypeName[1183:1194]:      GenericEmph,
	_TokenTypeLowerName[1183:1194]: GenericEmph,
	_TokenTypeName[1194:1206]:      GenericError,
	_TokenTypeLowerName[1194:1206]: GenericError,
	_TokenTypeName[1206:1220]:      GenericHeading,
	_TokenTypeLowerName[1206:1220]: GenericHeading,
	_TokenTypeName[1220:1235]:      GenericInserted,
	_TokenTypeLowerName[1220:1235]: GenericInserted,
	_TokenTypeName[1235:1248]:      GenericOutput,
	_TokenTypeLowerName[1235:1248]: GenericOutput,
	_TokenTypeName[1248:1261]:      GenericPrompt,
	_TokenTypeLowerName[1248:1261]: GenericPrompt,
	_TokenTypeName[1261:1274]:      GenericStrong,
	_TokenTypeLowerName[1261:1274]: GenericStrong,
	_TokenTypeName[1274:1291]:      GenericSubheading,
	_TokenTypeLowerName[1274:1291]: GenericSubheading,
	_TokenTypeName[1291:1307]:      GenericTraceback,
	_TokenTypeLowerName[1291:1307]: GenericTraceback,
	_TokenTypeName[1307:1323]:      GenericUnderline,
	_TokenTypeLowerName[1307:1323]: GenericUnderline,
	_TokenTypeName[1323:1327]:      Text,
	_TokenTypeLowerName[1323:1327]: Text,
	_TokenTypeName[1327:1341]:      TextWhitespace,
	_TokenTypeLowerName[1327:1341]: TextWhitespace,
	_TokenTypeName[1341:1351]:      TextSymbol,
	_TokenTypeLowerName[1341:1351]: TextSymbol,
	_TokenTypeName[1351:1366]:      TextPunctuation,
	_TokenTypeLowerName[1351:1366]: TextPunctuation,
}

var _TokenTypeNames = []string{
	_TokenTypeName[0:6],
	_TokenTypeName[6:10],
	_TokenTypeName[10:15],
	_TokenTypeName[15:20],
	_TokenTypeName[20:28],
	_TokenTypeName[28:36],
	_TokenTypeName[36:47],
	_TokenTypeName[47:56],
	_TokenTypeName[56:69],
	_TokenTypeName[69:85],
	_TokenTypeName[85:96],
	_TokenTypeName[96:100],
	_TokenTypeName[100:110],
	_TokenTypeName[110:120],
	_TokenTypeName[120:127],
	_TokenTypeName[127:142],
	_TokenTypeName[142:160],
	_TokenTypeName[160:176],
	_TokenTypeName[176:189],
	_TokenTypeName[189:204],
	_TokenTypeName[204:215],
	_TokenTypeName[215:219],
	_TokenTypeName[219:232],
	_TokenTypeName[232:241],
	_TokenTypeName[241:253],
	_TokenTypeName[253:266],
	_TokenTypeName[266:276],
	_TokenTypeName[276:289],
	_TokenTypeName[289:300],
	_TokenTypeName[300:309],
	_TokenTypeName[309:322],
	_TokenTypeName[322:334],
	_TokenTypeName[334:343],
	_TokenTypeName[343:353],
	_TokenTypeName[353:365],
	_TokenTypeName[365:372],
	_TokenTypeName[372:383],
	_TokenTypeName[383:400],
	_TokenTypeName[400:412],
	_TokenTypeName[412:433],
	_TokenTypeName[433:450],
	_TokenTypeName[450:468],
	_TokenTypeName[468:488],
	_TokenTypeName[488:505],
	_TokenTypeName[505:517],
	_TokenTypeName[517:534],
	_TokenTypeName[534:541],
	_TokenTypeName[541:552],
	_TokenTypeName[552:564],
	_TokenTypeName[564:577],
	_TokenTypeName[577:595],
	_TokenTypeName[595:612],
	_TokenTypeName[612:633],
	_TokenTypeName[633:653],
	_TokenTypeName[653:670],
	_TokenTypeName[670:692],
	_TokenTypeName[692:708],
	_TokenTypeName[708:727],
	_TokenTypeName[727:746],
	_TokenTypeName[746:766],
	_TokenTypeName[766:787],
	_TokenTypeName[787:804],
	_TokenTypeName[804:822],
	_TokenTypeName[822:840],
	_TokenTypeName[840:859],
	_TokenTypeName[859:878],
	_TokenTypeName[878:891],
	_TokenTypeName[891:907],
	_TokenTypeName[907:925],
	_TokenTypeName[925:941],
	_TokenTypeName[941:961],
	_TokenTypeName[961:985],
	_TokenTypeName[985:1001],
	_TokenTypeName[1001:1018],
	_TokenTypeName[1018:1026],
	_TokenTypeName[1026:1038],
	_TokenTypeName[1038:1054],
	_TokenTypeName[1054:1065],
	_TokenTypeName[1065:1072],
	_TokenTypeName[1072:1087],
	_TokenTypeName[1087:1103],
	_TokenTypeName[1103:1116],
	_TokenTypeName[1116:1130],
	_TokenTypeName[1130:1144],
	_TokenTypeName[1144:1162],
	_TokenTypeName[1162:1169],
	_TokenTypeName[1169:1183],
	_TokenTypeName[1183:1194],
	_TokenTypeName[1194:1206],
	_TokenTypeName[1206:1220],
	_TokenTypeName[1220:1235],
	_TokenTypeName[1235:1248],
	_TokenTypeName[1248:1261],
	_TokenTypeName[1261:1274],
	_TokenTypeName[1274:1291],
	_TokenTypeName[1291:1307],
	_TokenTypeName[1307:1323],
	_TokenTypeName[1323:1327],
	_TokenTypeName[1327:1341],
	_TokenTypeName[1341:1351],
	_TokenTypeName[1351:1366],
}

// TokenTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TokenTypeString(s string) (TokenType, error) {
	if val, ok := _TokenTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TokenTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TokenType values", s)
}

// TokenTypeValues returns all values of the enum
func TokenTypeValues() []TokenType {
	return _TokenTypeValues
}

// TokenTypeStrings returns a slice of all String values of the enum
func TokenTypeStrings() []string {
	strs := make([]string, len(_TokenTypeNames))
	copy(strs, _TokenTypeNames)
	return strs
}

// IsATokenType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TokenType) IsATokenType() bool {
	_, ok := _TokenTypeMap[i]
	return ok
}

// MarshalText implements the encoding.TextMarshaler interface for TokenType
func (i TokenType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for TokenType
func (i *TokenType) UnmarshalText(text []byte) error {
	var err error
	*i, err = TokenTypeString(string(text))
	return err
}
