// Code generated by "go generate" (internal/metadatagen); DO NOT EDIT.

package lexers

import (
	"github.com/alecthomas/chroma/v3"
)

// embeddedLexers mirrors the <config> element of every XML lexer definition
// under embedded/, so that the registry can be built without parsing XML at
// init time. TestEmbeddedLexerMetadata verifies it is up to date.
var embeddedLexers = []struct {
	path   string
	config chroma.Config
}{
	{"embedded/abap.xml", chroma.Config{
		Name: "ABAP",
		Aliases: []string{
			"abap",
		},
		Filenames: []string{
			"*.abap",
			"*.ABAP",
		},
		MimeTypes: []string{
			"text/x-abap",
		},
		CaseInsensitive: true,
	}},
	{"embedded/abnf.xml", chroma.Config{
		Name: "ABNF",
		Aliases: []string{
			"abnf",
		},
		Filenames: []string{
			"*.abnf",
		},
		MimeTypes: []string{
			"text/x-abnf",
		},
	}},
	{"embedded/actionscript.xml", chroma.Config{
		Name: "ActionScript",
		Aliases: []string{
			"as",
			"actionscript",
		},
		Filenames: []string{
			"*.as",
		},
		MimeTypes: []string{
			"application/x-actionscript",
			"text/x-actionscript",
			"text/actionscript",
		},
		DotAll:       true,
		NotMultiline: true,
	}},
	{"embedded/actionscript_3.xml", chroma.Config{
		Name: "ActionScript 3",
		Aliases: []string{
			"as3",
			"actionscript3",
		},
		Filenames: []string{
			"*.as",
		},
		MimeTypes: []string{
			"application/x-actionscript3",
			"text/x-actionscript3",
			"text/actionscript3",
		},
		DotAll: true,
	}},
	{"embedded/ada.xml", chroma.Config{
		Name: "Ada",
		Aliases: []string{
			"ada",
			"ada95",
			"ada2005",
		},
		Filenames: []string{
			"*.adb",
			"*.ads",
			"*.ada",
		},
		MimeTypes: []string{
			"text/x-ada",
		},
		CaseInsensitive: true,
	}},
	{"embedded/agda.xml", chroma.Config{
		Name: "Agda",
		Aliases: []string{
			"agda",
		},
		Filenames: []string{
			"*.agda",
		},
		MimeTypes: []string{
			"text/x-agda",
		},
	}},
	{"embedded/al.xml", chroma.Config{
		Name: "AL",
		Aliases: []string{
			"al",
		},
		Filenames: []string{
			"*.al",
			"*.dal",
		},
		MimeTypes: []string{
			"text/x-al",
		},
		CaseInsensitive: true,
		DotAll:          true,
	}},
	{"embedded/alloy.xml", chroma.Config{
		Name: "Alloy",
		Aliases: []string{
			"alloy",
		},
		Filenames: []string{
			"*.als",
		},
		MimeTypes: []string{
			"text/x-alloy",
		},
		DotAll: true,
	}},
	{"embedded/ampl.xml", chroma.Config{
		Name: "AMPL",
		Aliases: []string{
			"ampl",
		},
		Filenames: []string{
			"*.mod",
			"*.run",
		},
		MimeTypes: []string{
			"text/x-ampl",
		},
		DotAll: true,
	}},
	{"embedded/angular2.xml", chroma.Config{
		Name: "Angular2",
		Aliases: []string{
			"ng2",
		},
	}},
	{"embedded/antlr.xml", chroma.Config{
		Name: "ANTLR",
		Aliases: []string{
			"antlr",
		},
	}},
	{"embedded/apacheconf.xml", chroma.Config{
		Name: "ApacheConf",
		Aliases: []string{
			"apacheconf",
			"aconf",
			"apache",
		},
		Filenames: []string{
			".htaccess",
			"apache.conf",
			"apache2.conf",
		},
		MimeTypes: []string{
			"text/x-apacheconf",
		},
		CaseInsensitive: true,
	}},
	{"embedded/apl.xml", chroma.Config{
		Name: "APL",
		Aliases: []string{
			"apl",
		},
		Filenames: []string{
			"*.apl",
		},
	}},
	{"embedded/applescript.xml", chroma.Config{
		Name: "AppleScript",
		Aliases: []string{
			"applescript",
		},
		Filenames: []string{
			"*.applescript",
		},
		DotAll: true,
	}},
	{"embedded/arangodb_aql.xml", chroma.Config{
		Name: "ArangoDB AQL",
		Aliases: []string{
			"aql",
		},
		Filenames: []string{
			"*.aql",
		},
		MimeTypes: []string{
			"text/x-aql",
		},
		CaseInsensitive: true,
		DotAll:          true,
		EnsureNL:        true,
	}},
	{"embedded/arduino.xml", chroma.Config{
		Name: "Arduino",
		Aliases: []string{
			"arduino",
		},
		Filenames: []string{
			"*.ino",
		},
		MimeTypes: []string{
			"text/x-arduino",
		},
		EnsureNL: true,
	}},
	{"embedded/armasm.xml", chroma.Config{
		Name: "ArmAsm",
		Aliases: []string{
			"armasm",
		},
		Filenames: []string{
			"*.s",
			"*.S",
		},
		MimeTypes: []string{
			"text/x-armasm",
			"text/x-asm",
		},
		EnsureNL: true,
	}},
	{"embedded/arturo.xml", chroma.Config{
		Name: "Arturo",
		Aliases: []string{
			"arturo",
			"art",
		},
		Filenames: []string{
			"*.art",
		},
	}},
	{"embedded/astro.xml", chroma.Config{
		Name: "Astro",
		Aliases: []string{
			"astro",
		},
		Filenames: []string{
			"*.astro",
		},
		MimeTypes: []string{
			"text/x-astro",
		},
		CaseInsensitive: true,
		DotAll:          true,
	}},
	{"embedded/atl.xml", chroma.Config{
		Name: "ATL",
		Aliases: []string{
			"atl",
		},
		Filenames: []string{
			"*.atl",
		},
		MimeTypes: []string{
			"text/x-atl",
		},
		DotAll: true,
	}},
	{"embedded/autohotkey.xml", chroma.Config{
		Name: "AutoHotkey",
		Aliases: []string{
			"autohotkey",
			"ahk",
		},
		Filenames: []string{
			"*.ahk",
			"*.ahkl",
		},
		MimeTypes: []string{
			"text/x-autohotkey",
		},
	}},
	{"embedded/autoit.xml", chroma.Config{
		Name: "AutoIt",
		Aliases: []string{
			"autoit",
		},
		Filenames: []string{
			"*.au3",
		},
		MimeTypes: []string{
			"text/x-autoit",
		},
	}},
	{"embedded/awk.xml", chroma.Config{
		Name: "Awk",
		Aliases: []string{
			"awk",
			"gawk",
			"mawk",
			"nawk",
		},
		Filenames: []string{
			"*.awk",
		},
		MimeTypes: []string{
			"application/x-awk",
		},
	}},
	{"embedded/ballerina.xml", chroma.Config{
		Name: "Ballerina",
		Aliases: []string{
			"ballerina",
		},
		Filenames: []string{
			"*.bal",
		},
		MimeTypes: []string{
			"text/x-ballerina",
		},
		DotAll: true,
	}},
	{"embedded/bash.xml", chroma.Config{
		Name: "Bash",
		Aliases: []string{
			"bash",
			"sh",
			"ksh",
			"zsh",
			"shell",
		},
		Filenames: []string{
			"*.sh",
			"*.ksh",
			"*.bash",
			"*.ebuild",
			"*.eclass",
			".env",
			".env.*",
			"*.env",
			"*.exheres-0",
			"*.exlib",
			"*.zsh",
			"*.zshrc",
			".bashrc",
			"bashrc",
			".bash_*",
			"bash_*",
			"zshrc",
			".zshrc",
			"APKBUILD",
			"PKGBUILD",
		},
		MimeTypes: []string{
			"application/x-sh",
			"application/x-shellscript",
		},
		Analyse: &chroma.AnalyseConfig{
			Regexes: []chroma.RegexConfig{
				{
					Pattern: "(?m)^#!.*/bin/(?:env |)(?:bash|zsh|sh|ksh)",
					Score:   1,
				},
			},
			First: true,
		},
	}},
	{"embedded/bash_session.xml", chroma.Config{
		Name: "Bash Session",
		Aliases: []string{
			"bash-session",
			"console",
			"shell-session",
		},
		Filenames: []string{
			"*.sh-session",
		},
		MimeTypes: []string{
			"text/x-sh",
		},
		EnsureNL: true,
	}},
	{"embedded/batchfile.xml", chroma.Config{
		Name: "Batchfile",
		Aliases: []string{
			"bat",
			"batch",
			"dosbatch",
			"winbatch",
		},
		Filenames: []string{
			"*.bat",
			"*.cmd",
		},
		MimeTypes: []string{
			"application/x-dos-batch",
		},
		CaseInsensitive: true,
	}},
	{"embedded/beef.xml", chroma.Config{
		Name: "Beef",
		Aliases: []string{
			"beef",
		},
		Filenames: []string{
			"*.bf",
		},
		MimeTypes: []string{
			"text/x-beef",
		},
		DotAll:   true,
		EnsureNL: true,
	}},
	{"embedded/bibtex.xml", chroma.Config{
		Name: "BibTeX",
		Aliases: []string{
			"bib",
			"bibtex",
		},
		Filenames: []string{
			"*.bib",
		},
		MimeTypes: []string{
			"text/x-bibtex",
		},
		CaseInsensitive: true,
		NotMultiline:    true,
	}},
	{"embedded/bicep.xml", chroma.Config{
		Name: "Bicep",
		Aliases: []string{
			"bicep",
		},
		Filenames: []string{
			"*.bicep",
		},
	}},
	{"embedded/blitzbasic.xml", chroma.Config{
		Name: "BlitzBasic",
		Aliases: []string{
			"blitzbasic",
			"b3d",
			"bplus",
		},
		Filenames: []string{
			"*.bb",
			"*.decls",
		},
		MimeTypes: []string{
			"text/x-bb",
		},
		CaseInsensitive: true,
	}},
	{"embedded/bnf.xml", chroma.Config{
		Name: "BNF",
		Aliases: []string{
			"bnf",
		},
		Filenames: []string{
			"*.bnf",
		},
		MimeTypes: []string{
			"text/x-bnf",
		},
	}},
	{"embedded/bqn.xml", chroma.Config{
		Name: "BQN",
		Aliases: []string{
			"bqn",
		},
		Filenames: []string{
			"*.bqn",
		},
	}},
	{"embedded/brainfuck.xml", chroma.Config{
		Name: "Brainfuck",
		Aliases: []string{
			"brainfuck",
			"bf",
		},
		Filenames: []string{
			"*.bf",
			"*.b",
		},
		MimeTypes: []string{
			"application/x-brainfuck",
		},
	}},
	{"embedded/c#.xml", chroma.Config{
		Name: "C#",
		Aliases: []string{
			"csharp",
			"c#",
		},
		Filenames: []string{
			"*.cs",
		},
		MimeTypes: []string{
			"text/x-csharp",
		},
		DotAll:   true,
		EnsureNL: true,
	}},
	{"embedded/c++.xml", chroma.Config{
		Name: "C++",
		Aliases: []string{
			"cpp",
			"c++",
		},
		Filenames: []string{
			"*.cpp",
			"*.hpp",
			"*.c++",
			"*.h++",
			"*.cc",
			"*.hh",
			"*.cxx",
			"*.hxx",
			"*.C",
			"*.H",
			"*.cp",
			"*.CPP",
			"*.tpp",
		},
		MimeTypes: []string{
			"text/x-c++hdr",
			"text/x-c++src",
		},
		EnsureNL: true,
		Analyse: &chroma.AnalyseConfig{
			Regexes: []chroma.RegexConfig{
				{
					Pattern: "#include <[a-z_]+>",
					Score:   0.2,
				},
				{
					Pattern: "using namespace ",
					Score:   0.4,
				},
			},
			First: true,
		},
	}},
	{"embedded/c.xml", chroma.Config{
		Name: "C",
		Aliases: []string{
			"c",
		},
		Filenames: []string{
			"*.c",
			"*.h",
			"*.idc",
			"*.x[bp]m",
		},
		MimeTypes: []string{
			"text/x-chdr",
			"text/x-csrc",
			"image/x-xbitmap",
			"image/x-xpixmap",
		},
		EnsureNL: true,
		Analyse: &chroma.AnalyseConfig{
			Regexes: []chroma.RegexConfig{
				{
					Pattern: "(?m)^\\s*#include <",
					Score:   0.1,
				},
				{
					Pattern: "(?m)^\\s*#ifn?def ",
					Score:   0.1,
				},
			},
			First: true,
		},
	}},
	{"embedded/c3.xml", chroma.Config{
		Name: "C3",
		Aliases: []string{
			"c3",
		},
		Filenames: []string{
			"*.c3",
			"*.c3i",
			"*.c3t",
		},
		DotAll: true,
	}},
	{"embedded/cap_n_proto.xml", chroma.Config{
		Name: "Cap'n Proto",
		Aliases: []string{
			"capnp",
		},
		Filenames: []string{
			"*.capnp",
		},
	}},
	{"embedded/cassandra_cql.xml", chroma.Config{
		Name: "Cassandra CQL",
		Aliases: []string{
			"cassandra",
			"cql",
		},
		Filenames: []string{
			"*.cql",
		},
		MimeTypes: []string{
			"text/x-cql",
		},
		CaseInsensitive: true,
		NotMultiline:    true,
	}},
	{"embedded/cedar.xml", chroma.Config{
		Name: "Cedar",
		Aliases: []string{
			"cedar",
		},
		Filenames: []string{
			"*.cedar",
		},
		MimeTypes: []string{
			"text/x-cedar",
		},
		EnsureNL: true,
	}},
	{"embedded/ceylon.xml", chroma.Config{
		Name: "Ceylon",
		Aliases: []string{
			"ceylon",
		},
		Filenames: []string{
			"*.ceylon",
		},
		MimeTypes: []string{
			"text/x-ceylon",
		},
		DotAll: true,
	}},
	{"embedded/cfengine3.xml", chroma.Config{
		Name: "CFEngine3",
		Aliases: []string{
			"cfengine3",
			"cf3",
		},
		Filenames: []string{
			"*.cf",
		},
	}},
	{"embedded/cfstatement.xml", chroma.Config{
		Name: "cfstatement",
		Aliases: []string{
			"cfs",
		},
		CaseInsensitive: true,
		NotMultiline:    true,
	}},
	{"embedded/chaiscript.xml", chroma.Config{
		Name: "ChaiScript",
		Aliases: []string{
			"chai",
			"chaiscript",
		},
		Filenames: []string{
			"*.chai",
		},
		MimeTypes: []string{
			"text/x-chaiscript",
			"application/x-chaiscript",
		},
		DotAll: true,
	}},
	{"embedded/chapel.xml", chroma.Config{
		Name: "Chapel",
		Aliases: []string{
			"chapel",
			"chpl",
		},
		Filenames: []string{
			"*.chpl",
		},
	}},
	{"embedded/cheetah.xml", chroma.Config{
		Name: "Cheetah",
		Aliases: []string{
			"cheetah",
			"spitfire",
		},
		Filenames: []string{
			"*.tmpl",
			"*.spt",
		},
		MimeTypes: []string{
			"application/x-cheetah",
			"application/x-spitfire",
		},
	}},
	{"embedded/clojure.xml", chroma.Config{
		Name: "Clojure",
		Aliases: []string{
			"clojure",
			"clj",
			"edn",
		},
		Filenames: []string{
			"*.clj",
			"*.edn",
		},
		MimeTypes: []string{
			"text/x-clojure",
			"application/x-clojure",
			"application/edn",
		},
	}},
	{"embedded/cmake.xml", chroma.Config{
		Name: "CMake",
		Aliases: []string{
			"cmake",
		},
		Filenames: []string{
			"*.cmake",
			"CMakeLists.txt",
		},
		MimeTypes: []string{
			"text/x-cmake",
		},
	}},
	{"embedded/cobol.xml", chroma.Config{
		Name: "COBOL",
		Aliases: []string{
			"cobol",
		},
		Filenames: []string{
			"*.cob",
			"*.COB",
			"*.cpy",
			"*.CPY",
		},
		MimeTypes: []string{
			"text/x-cobol",
		},
		CaseInsensitive: true,
	}},
	{"embedded/coffeescript.xml", chroma.Config{
		Name: "CoffeeScript",
		Aliases: []string{
			"coffee-script",
			"coffeescript",
			"coffee",
		},
		Filenames: []string{
			"*.coffee",
		},
		MimeTypes: []string{
			"text/coffeescript",
		},
		DotAll:       true,
		NotMultiline: true,
	}},
	{"embedded/common_lisp.xml", chroma.Config{
		Name: "Common Lisp",
		Aliases: []string{
			"common-lisp",
			"cl",
			"lisp",
		},
		Filenames: []string{
			"*.cl",
			"*.lisp",
		},
		MimeTypes: []string{
			"text/x-common-lisp",
		},
		CaseInsensitive: true,
	}},
	{"embedded/coq.xml", chroma.Config{
		Name: "Coq",
		Aliases: []string{
			"coq",
		},
		Filenames: []string{
			"*.v",
		},
		MimeTypes: []string{
			"text/x-coq",
		},
	}},
	{"embedded/core.xml", chroma.Config{
		Name: "Core",
		Aliases: []string{
			"core",
		},
		Filenames: []string{
			"*.core",
		},
		MimeTypes: []string{
			"text/x-core",
		},
	}},
	{"embedded/crystal.xml", chroma.Config{
		Name: "Crystal",
		Aliases: []string{
			"cr",
			"crystal",
		},
		Filenames: []string{
			"*.cr",
		},
		MimeTypes: []string{
			"text/x-crystal",
		},
		DotAll: true,
	}},
	{"embedded/css.xml", chroma.Config{
		Name: "CSS",
		Aliases: []string{
			"css",
		},
		Filenames: []string{
			"*.css",
		},
		MimeTypes: []string{
			"text/css",
		},
	}},
	{"embedded/csv.xml", chroma.Config{
		Name: "CSV",
		Aliases: []string{
			"csv",
		},
		Filenames: []string{
			"*.csv",
		},
		MimeTypes: []string{
			"text/csv",
		},
	}},
	{"embedded/cue.xml", chroma.Config{
		Name: "CUE",
		Aliases: []string{
			"cue",
		},
		Filenames: []string{
			"*.cue",
		},
		MimeTypes: []string{
			"text/x-cue",
		},
		DotAll:   true,
		EnsureNL: true,
	}},
	{"embedded/cython.xml", chroma.Config{
		Name: "Cython",
		Aliases: []string{
			"cython",
			"pyx",
			"pyrex",
		},
		Filenames: []string{
			"*.pyx",
			"*.pxd",
			"*.pxi",
		},
		MimeTypes: []string{
			"text/x-cython",
			"application/x-cython",
		},
	}},
	{"embedded/d.xml", chroma.Config{
		Name: "D",
		Aliases: []string{
			"d",
		},
		Filenames: []string{
			"*.d",
			"*.di",
		},
		MimeTypes: []string{
			"text/x-d",
		},
		EnsureNL: true,
	}},
	{"embedded/dart.xml", chroma.Config{
		Name: "Dart",
		Aliases: []string{
			"dart",
		},
		Filenames: []string{
			"*.dart",
		},
		MimeTypes: []string{
			"text/x-dart",
		},
		DotAll: true,
	}},
	{"embedded/dax.xml", chroma.Config{
		Name: "Dax",
		Aliases: []string{
			"dax",
		},
		Filenames: []string{
			"*.dax",
		},
	}},
	{"embedded/desktop_entry.xml", chroma.Config{
		Name: "Desktop file",
		Aliases: []string{
			"desktop",
			"desktop_entry",
		},
		Filenames: []string{
			"*.desktop",
		},
		MimeTypes: []string{
			"application/x-desktop",
		},
	}},
	{"embedded/devicetree.xml", chroma.Config{
		Name: "Devicetree",
		Aliases: []string{
			"devicetree",
			"dts",
		},
		Filenames: []string{
			"*.dts",
			"*.dtsi",
		},
		MimeTypes: []string{
			"text/x-devicetree",
		},
	}},
	{"embedded/diff.xml", chroma.Config{
		Name: "Diff",
		Aliases: []string{
			"diff",
			"udiff",
		},
		Filenames: []string{
			"*.diff",
			"*.patch",
		},
		MimeTypes: []string{
			"text/x-diff",
			"text/x-patch",
		},
		EnsureNL: true,
	}},
	{"embedded/django_jinja.xml", chroma.Config{
		Name: "Django/Jinja",
		Aliases: []string{
			"django",
			"jinja",
		},
		MimeTypes: []string{
			"application/x-django-templating",
			"application/x-jinja",
		},
		DotAll: true,
	}},
	{"embedded/dns.xml", chroma.Config{
		Name: "dns",
		Aliases: []string{
			"zone",
			"bind",
		},
		Filenames: []string{
			"*.zone",
		},
		MimeTypes: []string{
			"text/dns",
		},
		Analyse: &chroma.AnalyseConfig{
			Regexes: []chroma.RegexConfig{
				{
					Pattern: "(?m)^@\\s+IN\\s+SOA\\s+",
					Score:   1,
				},
			},
			First: true,
		},
	}},
	{"embedded/docker.xml", chroma.Config{
		Name: "Docker",
		Aliases: []string{
			"docker",
			"dockerfile",
			"containerfile",
		},
		Filenames: []string{
			"Dockerfile",
			"Dockerfile.*",
			"*.Dockerfile",
			"*.docker",
			"Containerfile",
			"Containerfile.*",
			"*.Containerfile",
		},
		MimeTypes: []string{
			"text/x-dockerfile-config",
		},
		CaseInsensitive: true,
	}},
	{"embedded/dtd.xml", chroma.Config{
		Name: "DTD",
		Aliases: []string{
			"dtd",
		},
		Filenames: []string{
			"*.dtd",
		},
		MimeTypes: []string{
			"application/xml-dtd",
		},
		DotAll: true,
	}},
	{"embedded/dylan.xml", chroma.Config{
		Name: "Dylan",
		Aliases: []string{
			"dylan",
		},
		Filenames: []string{
			"*.dylan",
			"*.dyl",
			"*.intr",
		},
		MimeTypes: []string{
			"text/x-dylan",
		},
		CaseInsensitive: true,
	}},
	{"embedded/ebnf.xml", chroma.Config{
		Name: "EBNF",
		Aliases: []string{
			"ebnf",
		},
		Filenames: []string{
			"*.ebnf",
		},
		MimeTypes: []string{
			"text/x-ebnf",
		},
	}},
	{"embedded/elixir.xml", chroma.Config{
		Name: "Elixir",
		Aliases: []string{
			"elixir",
			"ex",
			"exs",
		},
		Filenames: []string{
			"*.ex",
			"*.eex",
			"*.exs",
		},
		MimeTypes: []string{
			"text/x-elixir",
		},
	}},
	{"embedded/elm.xml", chroma.Config{
		Name: "Elm",
		Aliases: []string{
			"elm",
		},
		Filenames: []string{
			"*.elm",
		},
		MimeTypes: []string{
			"text/x-elm",
		},
	}},
	{"embedded/emacslisp.xml", chroma.Config{
		Name: "EmacsLisp",
		Aliases: []string{
			"emacs",
			"elisp",
			"emacs-lisp",
		},
		Filenames: []string{
			"*.el",
		},
		MimeTypes: []string{
			"text/x-elisp",
			"application/x-elisp",
		},
	}},
	{"embedded/erb.xml", chroma.Config{
		Name:   "ERB",
		DotAll: true,
	}},
	{"embedded/erlang.xml", chroma.Config{
		Name: "Erlang",
		Aliases: []string{
			"erlang",
		},
		Filenames: []string{
			"*.erl",
			"*.hrl",
			"*.es",
			"*.escript",
		},
		MimeTypes: []string{
			"text/x-erlang",
		},
	}},
	{"embedded/factor.xml", chroma.Config{
		Name: "Factor",
		Aliases: []string{
			"factor",
		},
		Filenames: []string{
			"*.factor",
		},
		MimeTypes: []string{
			"text/x-factor",
		},
	}},
	{"embedded/fennel.xml", chroma.Config{
		Name: "Fennel",
		Aliases: []string{
			"fennel",
			"fnl",
		},
		Filenames: []string{
			"*.fennel",
		},
		MimeTypes: []string{
			"text/x-fennel",
			"application/x-fennel",
		},
	}},
	{"embedded/fish.xml", chroma.Config{
		Name: "Fish",
		Aliases: []string{
			"fish",
			"fishshell",
		},
		Filenames: []string{
			"*.fish",
			"*.load",
		},
		MimeTypes: []string{
			"application/x-fish",
		},
	}},
	{"embedded/forth.xml", chroma.Config{
		Name: "Forth",
		Aliases: []string{
			"forth",
		},
		Filenames: []string{
			"*.frt",
			"*.fth",
			"*.fs",
		},
		MimeTypes: []string{
			"application/x-forth",
		},
		CaseInsensitive: true,
	}},
	{"embedded/fortran.xml", chroma.Config{
		Name: "Fortran",
		Aliases: []string{
			"fortran",
			"f90",
		},
		Filenames: []string{
			"*.f03",
			"*.f90",
			"*.f95",
			"*.F03",
			"*.F90",
			"*.F95",
		},
		MimeTypes: []string{
			"text/x-fortran",
		},
		CaseInsensitive: true,
	}},
	{"embedded/fortranfixed.xml", chroma.Config{
		Name: "FortranFixed",
		Aliases: []string{
			"fortranfixed",
		},
		Filenames: []string{
			"*.f",
			"*.F",
		},
		MimeTypes: []string{
			"text/x-fortran",
		},
		CaseInsensitive: true,
		NotMultiline:    true,
	}},
	{"embedded/fsharp.xml", chroma.Config{
		Name: "FSharp",
		Aliases: []string{
			"fsharp",
		},
		Filenames: []string{
			"*.fs",
			"*.fsi",
		},
		MimeTypes: []string{
			"text/x-fsharp",
		},
		Analyse: &chroma.AnalyseConfig{
			Regexes: []chroma.RegexConfig{
				{
					Pattern: "(?m)^\\s*(let rec|let|module|open)\\b",
					Score:   0.4,
				},
				{
					Pattern: "\\|>",
					Score:   0.1,
				},
			},
		},
	}},
	{"embedded/garden.xml", chroma.Config{
		Name: "Garden",
		Aliases: []string{
			"garden",
		},
		Filenames: []string{
			"*.garden",
		},
		MimeTypes: []string{
			"text/x-garden",
		},
		EnsureNL: true,
	}},
	{"embedded/gas.xml", chroma.Config{
		Name: "GAS",
		Aliases: []string{
			"gas",
			"asm",
		},
		Filenames: []string{
			"*.s",
			"*.S",
		},
		MimeTypes: []string{
			"text/x-gas",
		},
		Priority: 0.1,
	}},
	{"embedded/gdscript.xml", chroma.Config{
		Name: "GDScript",
		Aliases: []string{
			"gdscript",
			"gd",
		},
		Filenames: []string{
			"*.gd",
		},
		MimeTypes: []string{
			"text/x-gdscript",
			"application/x-gdscript",
		},
		Priority: 0.1,
		Analyse: &chroma.AnalyseConfig{
			Regexes: []chroma.RegexConfig{
				{
					Pattern: "^export",
					Score:   0.1,
				},
			},
		},
	}},
	{"embedded/gdscript3.xml", chroma.Config{
		Name: "GDScript3",
		Aliases: []string{
			"gdscript3",
			"gd3",
		},
		Filenames: []string{
			"*.gd",
		},
		MimeTypes: []string{
			"text/x-gdscript",
			"application/x-gdscript",
		},
		Priority: 0.05,
		Analyse: &chroma.AnalyseConfig{
			Regexes: []chroma.RegexConfig{
				{
					Pattern: "func (_ready|_init|_input|_process|_unhandled_input)",
					Score:   0.8,
				},
				{
					Pattern: "(extends |class_name |onready |preload|load|setget|func [^_])",
					Score:   0.4,
				},
				{
					Pattern: "(var|const|enum|export|signal|tool)",
					Score:   0.2,
				},
			},
		},
	}},
	{"embedded/gemfile_lock.xml", chroma.Config{
		Name: "Gemfile.lock",
		Aliases: []string{
			"gemfile-lock",
			"gemfilelock",
		},
		Filenames: []string{
			"Gemfile.lock",
			"*.gemfile.lock",
		},
	}},
	{"embedded/gettext.xml", chroma.Config{
		Name: "Gettext",
		Aliases: []string{
			"pot",
			"po",
		},
		Filenames: []string{
			"*.pot",
			"*.po",
		},
		MimeTypes: []string{
			"application/x-gettext",
			"text/x-gettext",
			"text/gettext",
		},
	}},
	{"embedded/gherkin.xml", chroma.Config{
		Name: "Gherkin",
		Aliases: []string{
			"cucumber",
			"Cucumber",
			"gherkin",
			"Gherkin",
		},
		Filenames: []string{
			"*.feature",
			"*.FEATURE",
		},
		MimeTypes: []string{
			"text/x-gherkin",
		},
	}},
	{"embedded/gleam.xml", chroma.Config{
		Name: "Gleam",
		Aliases: []string{
			"gleam",
		},
		Filenames: []string{
			"*.gleam",
		},
		MimeTypes: []string{
			"text/x-gleam",
		},
	}},
	{"embedded/glsl.xml", chroma.Config{
		Name: "GLSL",
		Aliases: []string{
			"glsl",
		},
		Filenames: []string{
			"*.vert",
			"*.frag",
			"*.geo",
		},
		MimeTypes: []string{
			"text/x-glslsrc",
		},
	}},
	{"embedded/gnuplot.xml", chroma.Config{
		Name: "Gnuplot",
		Aliases: []string{
			"gnuplot",
		},
		Filenames: []string{
			"*.plot",
			"*.plt",
		},
		MimeTypes: []string{
			"text/x-gnuplot",
		},
	}},
	{"embedded/go_template.xml", chroma.Config{
		Name: "Go Template",
		Aliases: []string{
			"go-template",
		},
		Filenames: []string{
			"*.gotmpl",
			"*.go.tmpl",
		},
	}},
	{"embedded/graphql.xml", chroma.Config{
		Name: "GraphQL",
		Aliases: []string{
			"graphql",
			"graphqls",
			"gql",
		},
		Filenames: []string{
			"*.graphql",
			"*.graphqls",
		},
	}},
	{"embedded/groff.xml", chroma.Config{
		Name: "Groff",
		Aliases: []string{
			"groff",
			"nroff",
			"man",
		},
		Filenames: []string{
			"*.[1-9]",
			"*.1p",
			"*.3pm",
			"*.man",
		},
		MimeTypes: []string{
			"application/x-troff",
			"text/troff",
		},
	}},
	{"embedded/groovy.xml", chroma.Config{
		Name: "Groovy",
		Aliases: []string{
			"groovy",
		},
		Filenames: []string{
			"*.groovy",
			"*.gradle",
		},
		MimeTypes: []string{
			"text/x-groovy",
		},
		DotAll: true,
	}},
	{"embedded/handlebars.xml", chroma.Config{
		Name: "Handlebars",
		Aliases: []string{
			"handlebars",
			"hbs",
		},
		Filenames: []string{
			"*.handlebars",
			"*.hbs",
		},
	}},
	{"embedded/hare.xml", chroma.Config{
		Name: "Hare",
		Aliases: []string{
			"hare",
		},
		Filenames: []string{
			"*.ha",
		},
		MimeTypes: []string{
			"text/x-hare",
		},
	}},
	{"embedded/haskell.xml", chroma.Config{
		Name: "Haskell",
		Aliases: []string{
			"haskell",
			"hs",
		},
		Filenames: []string{
			"*.hs",
		},
		MimeTypes: []string{
			"text/x-haskell",
		},
	}},
	{"embedded/hexdump.xml", chroma.Config{
		Name: "Hexdump",
		Aliases: []string{
			"hexdump",
		},
	}},
	{"embedded/hlb.xml", chroma.Config{
		Name: "HLB",
		Aliases: []string{
			"hlb",
		},
		Filenames: []string{
			"*.hlb",
		},
	}},
	{"embedded/hlsl.xml", chroma.Config{
		Name: "HLSL",
		Aliases: []string{
			"hlsl",
		},
		Filenames: []string{
			"*.hlsl",
			"*.hlsli",
			"*.cginc",
			"*.fx",
			"*.fxh",
		},
		MimeTypes: []string{
			"text/x-hlsl",
		},
	}},
	{"embedded/holyc.xml", chroma.Config{
		Name: "HolyC",
		Aliases: []string{
			"holyc",
		},
		Filenames: []string{
			"*.HC",
			"*.hc",
			"*.HH",
			"*.hh",
			"*.hc.z",
			"*.HC.Z",
		},
		MimeTypes: []string{
			"text/x-chdr",
			"text/x-csrc",
			"image/x-xbitmap",
			"image/x-xpixmap",
		},
		EnsureNL: true,
	}},
	{"embedded/html.xml", chroma.Config{
		Name: "HTML",
		Aliases: []string{
			"html",
		},
		Filenames: []string{
			"*.html",
			"*.htm",
			"*.xhtml",
			"*.xslt",
		},
		MimeTypes: []string{
			"text/html",
			"application/xhtml+xml",
		},
		CaseInsensitive: true,
		DotAll:          true,
		NotMultiline:    true,
	}},
	{"embedded/hurl.xml", chroma.Config{
		Name: "Hurl",
		Aliases: []string{
			"hurl",
		},
		Filenames: []string{
			"*.hurl",
		},
		MimeTypes: []string{
			"text/x-hurl",
		},
	}},
	{"embedded/hy.xml", chroma.Config{
		Name: "Hy",
		Aliases: []string{
			"hylang",
		},
		Filenames: []string{
			"*.hy",
		},
		MimeTypes: []string{
			"text/x-hy",
			"application/x-hy",
		},
	}},
	{"embedded/hyprlang.xml", chroma.Config{
		Name: "Hyprlang",
		Aliases: []string{
			"hyprlang",
			"hypr",
		},
		Filenames: []string{
			"hypr*.conf",
			"*.hypr",
		},
		MimeTypes: []string{
			"text/x-hyprlang",
		},
		Analyse: &chroma.AnalyseConfig{
			Regexes: []chroma.RegexConfig{
				{
					Pattern: "(?m)^\\s*(bind|bindm|monitor|workspace|windowrulev2?|exec(?:-once|-shutdown)?|execr(?:-once)?|source)\\s*=",
					Score:   0.6,
				},
				{
					Pattern: "(?m)^\\s*\\$[A-Za-z_]\\w*\\s*=",
					Score:   0.4,
				},
				{
					Pattern: "(?m)^\\s*(general|decoration|animations|input|device|binds|gestures|misc|master|dwindle|xwayland|opengl|render|ecosystem)\\s*(?::[^\\s{]+)?\\s*\\{",
					Score:   0.4,
				},
			},
		},
	}},
	{"embedded/idris.xml", chroma.Config{
		Name: "Idris",
		Aliases: []string{
			"idris",
			"idr",
		},
		Filenames: []string{
			"*.idr",
		},
		MimeTypes: []string{
			"text/x-idris",
		},
	}},
	{"embedded/igor.xml", chroma.Config{
		Name: "Igor",
		Aliases: []string{
			"igor",
			"igorpro",
		},
		Filenames: []string{
			"*.ipf",
		},
		MimeTypes: []string{
			"text/ipf",
		},
		CaseInsensitive: true,
	}},
	{"embedded/influxdb_line_protocol.xml", chroma.Config{
		Name: "InfluxDB Line Protocol",
		Aliases: []string{
			"lp",
			"line-protocol",
		},
		Filenames: []string{
			"*.lp",
		},
	}},
	{"embedded/ini.xml", chroma.Config{
		Name: "INI",
		Aliases: []string{
			"ini",
			"cfg",
			"dosini",
		},
		Filenames: []string{
			"*.ini",
			"*.cfg",
			"*.inf",
			"*.service",
			"*.socket",
			"*.container",
			"*.network",
			"*.build",
			"*.pod",
			"*.kube",
			"*.volume",
			"*.image",
			".gitconfig",
			".editorconfig",
			"pylintrc",
			".pylintrc",
		},
		MimeTypes: []string{
			"text/x-ini",
			"text/inf",
		},
		Priority: 0.1,
	}},
	{"embedded/io.xml", chroma.Config{
		Name: "Io",
		Aliases: []string{
			"io",
		},
		Filenames: []string{
			"*.io",
		},
		MimeTypes: []string{
			"text/x-iosrc",
		},
	}},
	{"embedded/iscdhcpd.xml", chroma.Config{
		Name: "ISCdhcpd",
		Aliases: []string{
			"iscdhcpd",
		},
		Filenames: []string{
			"dhcpd.conf",
		},
	}},
	{"embedded/j.xml", chroma.Config{
		Name: "J",
		Aliases: []string{
			"j",
		},
		Filenames: []string{
			"*.ijs",
		},
		MimeTypes: []string{
			"text/x-j",
		},
	}},
	{"embedded/janet.xml", chroma.Config{
		Name: "Janet",
		Aliases: []string{
			"janet",
		},
		Filenames: []string{
			"*.janet",
			"*.jdn",
		},
		MimeTypes: []string{
			"text/x-janet",
			"application/x-janet",
		},
	}},
	{"embedded/java.xml", chroma.Config{
		Name: "Java",
		Aliases: []string{
			"java",
		},
		Filenames: []string{
			"*.java",
		},
		MimeTypes: []string{
			"text/x-java",
		},
		DotAll: true,
	}},
	{"embedded/javascript.xml", chroma.Config{
		Name: "JavaScript",
		Aliases: []string{
			"js",
			"javascript",
		},
		Filenames: []string{
			"*.js",
			"*.jsm",
			"*.mjs",
			"*.cjs",
		},
		MimeTypes: []string{
			"application/javascript",
			"application/x-javascript",
			"text/x-javascript",
			"text/javascript",
		},
		DotAll:   true,
		EnsureNL: true,
	}},
	{"embedded/jq.xml", chroma.Config{
		Name: "JQ",
		Aliases: []string{
			"jq",
		},
		Filenames: []string{
			"*.jq",
		},
		MimeTypes: []string{
			"application/x-jq",
		},
		DotAll:   true,
		EnsureNL: true,
	}},
	{"embedded/json.xml", chroma.Config{
		Name: "JSON",
		Aliases: []string{
			"json",
			"jsonl",
		},
		Filenames: []string{
			"*.json",
			"*.jsonl",
			"*.jsonc",
			"*.json5",
			"*.avsc",
			".luaurc",
		},
		MimeTypes: []string{
			"application/json",
			"application/jsonl",
		},
		DotAll:       true,
		NotMultiline: true,
	}},
	{"embedded/jsonata.xml", chroma.Config{
		Name: "JSONata",
		Aliases: []string{
			"jsonata",
		},
		Filenames: []string{
			"*.jsonata",
		},
		DotAll: true,
	}},
	{"embedded/jsonnet.xml", chroma.Config{
		Name: "Jsonnet",
		Aliases: []string{
			"jsonnet",
		},
		Filenames: []string{
			"*.jsonnet",
			"*.libsonnet",
		},
	}},
	{"embedded/julia.xml", chroma.Config{
		Name: "Julia",
		Aliases: []string{
			"julia",
			"jl",
		},
		Filenames: []string{
			"*.jl",
		},
		MimeTypes: []string{
			"text/x-julia",
			"application/x-julia",
		},
	}},
	{"embedded/jungle.xml", chroma.Config{
		Name: "Jungle",
		Aliases: []string{
			"jungle",
		},
		Filenames: []string{
			"*.jungle",
		},
		MimeTypes: []string{
			"text/x-jungle",
		},
	}},
	{"embedded/kakoune.xml", chroma.Config{
		Name: "Kakoune",
		Aliases: []string{
			"kak",
			"kakoune",
			"kakrc",
			"kakscript",
		},
		Filenames: []string{
			"*.kak",
			"kakrc",
		},
		MimeTypes: []string{
			"application/x-sh",
			"application/x-shellscript",
			"text/x-shellscript",
		},
	}},
	{"embedded/kdl.xml", chroma.Config{
		Name: "KDL",
		Aliases: []string{
			"kdl",
		},
		Filenames: []string{
			"*.kdl",
		},
	}},
	{"embedded/kotlin.xml", chroma.Config{
		Name: "Kotlin",
		Aliases: []string{
			"kotlin",
		},
		Filenames: []string{
			"*.kt",
			"*.kts",
		},
		MimeTypes: []string{
			"text/x-kotlin",
		},
		DotAll: true,
	}},
	{"embedded/lateralus.xml", chroma.Config{
		Name: "Lateralus",
		Aliases: []string{
			"lateralus",
			"ltl",
		},
		Filenames: []string{
			"*.ltl",
		},
		MimeTypes: []string{
			"text/x-lateralus",
		},
		EnsureNL: true,
	}},
	{"embedded/lean.xml", chroma.Config{
		Name: "Lean4",
		Aliases: []string{
			"lean4",
			"lean",
		},
		Filenames: []string{
			"*.lean",
		},
		MimeTypes: []string{
			"text/x-lean4",
			"text/x-lean",
		},
	}},
	{"embedded/lighttpd_configuration_file.xml", chroma.Config{
		Name: "Lighttpd configuration file",
		Aliases: []string{
			"lighty",
			"lighttpd",
		},
		MimeTypes: []string{
			"text/x-lighttpd-conf",
		},
	}},
	{"embedded/lilypond.xml", chroma.Config{
		Name: "LilyPond",
		Aliases: []string{
			"lilypond",
		},
		Filenames: []string{
			"*.ly",
		},
		DotAll: true,
	}},
	{"embedded/llvm.xml", chroma.Config{
		Name: "LLVM",
		Aliases: []string{
			"llvm",
		},
		Filenames: []string{
			"*.ll",
		},
		MimeTypes: []string{
			"text/x-llvm",
		},
	}},
	{"embedded/lox.xml", chroma.Config{
		Name: "lox",
		Filenames: []string{
			"*.lox",
		},
		DotAll:   true,
		EnsureNL: true,
	}},
	{"embedded/lua.xml", chroma.Config{
		Name: "Lua",
		Aliases: []string{
			"lua",
		},
		Filenames: []string{
			"*.lua",
			"*.wlua",
		},
		MimeTypes: []string{
			"text/x-lua",
			"application/x-lua",
		},
	}},
	{"embedded/luau.xml", chroma.Config{
		Name: "Luau",
		Aliases: []string{
			"luau",
		},
		Filenames: []string{
			"*.luau",
		},
	}},
	{"embedded/makefile.xml", chroma.Config{
		Name: "Makefile",
		Aliases: []string{
			"make",
			"makefile",
			"mf",
			"bsdmake",
		},
		Filenames: []string{
			"*.mak",
			"*.mk",
			"Makefile",
			"makefile",
			"Makefile.*",
			"GNUmakefile",
			"BSDmakefile",
			"Justfile",
			"justfile",
			".justfile",
		},
		MimeTypes: []string{
			"text/x-makefile",
		},
		EnsureNL: true,
	}},
	{"embedded/mako.xml", chroma.Config{
		Name: "Mako",
		Aliases: []string{
			"mako",
		},
		Filenames: []string{
			"*.mao",
		},
		MimeTypes: []string{
			"application/x-mako",
		},
	}},
	{"embedded/mason.xml", chroma.Config{
		Name: "Mason",
		Aliases: []string{
			"mason",
		},
		Filenames: []string{
			"*.m",
			"*.mhtml",
			"*.mc",
			"*.mi",
			"autohandler",
			"dhandler",
		},
		MimeTypes: []string{
			"application/x-mason",
		},
		Priority: 0.1,
	}},
	{"embedded/materialize_sql_dialect.xml", chroma.Config{
		Name: "Materialize SQL dialect",
		Aliases: []string{
			"materialize",
			"mzsql",
		},
		MimeTypes: []string{
			"text/x-materializesql",
		},
		CaseInsensitive: true,
		NotMultiline:    true,
	}},
	{"embedded/mathematica.xml", chroma.Config{
		Name: "Mathematica",
		Aliases: []string{
			"mathematica",
			"mma",
			"nb",
		},
		Filenames: []string{
			"*.cdf",
			"*.m",
			"*.ma",
			"*.mt",
			"*.mx",
			"*.nb",
			"*.nbp",
			"*.wl",
		},
		MimeTypes: []string{
			"application/mathematica",
			"application/vnd.wolfram.mathematica",
			"application/vnd.wolfram.mathematica.package",
			"application/vnd.wolfram.cdf",
		},
	}},
	{"embedded/matlab.xml", chroma.Config{
		Name: "Matlab",
		Aliases: []string{
			"matlab",
		},
		Filenames: []string{
			"*.m",
		},
		MimeTypes: []string{
			"text/matlab",
		},
	}},
	{"embedded/mcfunction.xml", chroma.Config{
		Name: "MCFunction",
		Aliases: []string{
			"mcfunction",
			"mcf",
		},
		Filenames: []string{
			"*.mcfunction",
		},
		MimeTypes: []string{
			"text/mcfunction",
		},
	}},
	{"embedded/meson.xml", chroma.Config{
		Name: "Meson",
		Aliases: []string{
			"meson",
			"meson.build",
		},
		Filenames: []string{
			"meson.build",
			"meson.options",
			"meson_options.txt",
		},
		MimeTypes: []string{
			"text/x-meson",
		},
	}},
	{"embedded/metal.xml", chroma.Config{
		Name: "Metal",
		Aliases: []string{
			"metal",
		},
		Filenames: []string{
			"*.metal",
		},
		MimeTypes: []string{
			"text/x-metal",
		},
		EnsureNL: true,
	}},
	{"embedded/microcad.xml", chroma.Config{
		Name: "microcad",
		Aliases: []string{
			"µcad",
		},
		Filenames: []string{
			"*.µcad",
			"*.ucad",
			"*.mcad",
		},
		MimeTypes: []string{
			"text/microcad",
		},
		EnsureNL: true,
	}},
	{"embedded/minizinc.xml", chroma.Config{
		Name: "MiniZinc",
		Aliases: []string{
			"minizinc",
			"MZN",
			"mzn",
		},
		Filenames: []string{
			"*.mzn",
			"*.dzn",
			"*.fzn",
		},
		MimeTypes: []string{
			"text/minizinc",
		},
	}},
	{"embedded/mlir.xml", chroma.Config{
		Name: "MLIR",
		Aliases: []string{
			"mlir",
		},
		Filenames: []string{
			"*.mlir",
		},
		MimeTypes: []string{
			"text/x-mlir",
		},
	}},
	{"embedded/modelica.xml", chroma.Config{
		Name: "Modelica",
		Aliases: []string{
			"modelica",
		},
		Filenames: []string{
			"*.mo",
		},
		MimeTypes: []string{
			"text/x-modelica",
		},
		DotAll:   true,
		EnsureNL: true,
	}},
	{"embedded/modula-2.xml", chroma.Config{
		Name: "Modula-2",
		Aliases: []string{
			"modula2",
			"m2",
		},
		Filenames: []string{
			"*.def",
			"*.mod",
		},
		MimeTypes: []string{
			"text/x-modula2",
		},
		DotAll: true,
	}},
	{"embedded/mojo.xml", chroma.Config{
		Name: "Mojo",
		Aliases: []string{
			"mojo",
			"🔥",
		},
		Filenames: []string{
			"*.mojo",
			"*.🔥",
		},
		MimeTypes: []string{
			"text/x-mojo",
			"application/x-mojo",
		},
	}},
	{"embedded/monkeyc.xml", chroma.Config{
		Name: "MonkeyC",
		Aliases: []string{
			"monkeyc",
		},
		Filenames: []string{
			"*.mc",
		},
		MimeTypes: []string{
			"text/x-monkeyc",
		},
	}},
	{"embedded/moonbit.xml", chroma.Config{
		Name: "MoonBit",
		Aliases: []string{
			"moonbit",
			"mbt",
		},
		Filenames: []string{
			"*.mbt",
		},
		EnsureNL: true,
	}},
	{"embedded/moonscript.xml", chroma.Config{
		Name: "MoonScript",
		Aliases: []string{
			"moonscript",
			"moon",
		},
		Filenames: []string{
			"*.moon",
		},
		MimeTypes: []string{
			"text/x-moonscript",
			"application/x-moonscript",
		},
	}},
	{"embedded/morrowindscript.xml", chroma.Config{
		Name: "MorrowindScript",
		Aliases: []string{
			"morrowind",
			"mwscript",
		},
	}},
	{"embedded/myghty.xml", chroma.Config{
		Name: "Myghty",
		Aliases: []string{
			"myghty",
		},
		Filenames: []string{
			"*.myt",
			"autodelegate",
		},
		MimeTypes: []string{
			"application/x-myghty",
		},
	}},
	{"embedded/mysql.xml", chroma.Config{
		Name: "MySQL",
		Aliases: []string{
			"mysql",
			"mariadb",
		},
		Filenames: []string{
			"*.sql",
		},
		MimeTypes: []string{
			"text/x-mysql",
			"text/x-mariadb",
		},
		CaseInsensitive: true,
		NotMultiline:    true,
	}},
	{"embedded/nasm.xml", chroma.Config{
		Name: "NASM",
		Aliases: []string{
			"nasm",
		},
		Filenames: []string{
			"*.asm",
			"*.ASM",
			"*.nasm",
		},
		MimeTypes: []string{
			"text/x-nasm",
		},
		CaseInsensitive: true,
		Priority:        1,
	}},
	{"embedded/natural.xml", chroma.Config{
		Name: "Natural",
		Aliases: []string{
			"natural",
		},
		Filenames: []string{
			"*.NSN",
			"*.NSP",
			"*.NSS",
			"*.NSH",
			"*.NSG",
			"*.NSL",
			"*.NSA",
			"*.NSM",
			"*.NSC",
			"*.NS7",
		},
		MimeTypes: []string{
			"text/x-natural",
		},
		CaseInsensitive: true,
	}},
	{"embedded/ndisasm.xml", chroma.Config{
		Name: "NDISASM",
		Aliases: []string{
			"ndisasm",
		},
		MimeTypes: []string{
			"text/x-disasm",
		},
		CaseInsensitive: true,
		Priority:        0.5,
	}},
	{"embedded/newspeak.xml", chroma.Config{
		Name: "Newspeak",
		Aliases: []string{
			"newspeak",
		},
		Filenames: []string{
			"*.ns2",
		},
		MimeTypes: []string{
			"text/x-newspeak",
		},
	}},
	{"embedded/nginx_configuration_file.xml", chroma.Config{
		Name: "Nginx configuration file",
		Aliases: []string{
			"nginx",
		},
		Filenames: []string{
			"nginx.conf",
		},
		MimeTypes: []string{
			"text/x-nginx-conf",
		},
	}},
	{"embedded/nim.xml", chroma.Config{
		Name: "Nim",
		Aliases: []string{
			"nim",
			"nimrod",
		},
		Filenames: []string{
			"*.nim",
			"*.nimrod",
		},
		MimeTypes: []string{
			"text/x-nim",
		},
		CaseInsensitive: true,
	}},
	{"embedded/nix.xml", chroma.Config{
		Name: "Nix",
		Aliases: []string{
			"nixos",
			"nix",
		},
		Filenames: []string{
			"*.nix",
		},
		MimeTypes: []string{
			"text/x-nix",
		},
	}},
	{"embedded/nsis.xml", chroma.Config{
		Name: "NSIS",
		Aliases: []string{
			"nsis",
			"nsi",
			"nsh",
		},
		Filenames: []string{
			"*.nsi",
			"*.nsh",
		},
		MimeTypes: []string{
			"text/x-nsis",
		},
		CaseInsensitive: true,
		NotMultiline:    true,
	}},
	{"embedded/nu.xml", chroma.Config{
		Name: "Nu",
		Aliases: []string{
			"nu",
		},
		Filenames: []string{
			"*.nu",
		},
		MimeTypes: []string{
			"application/x-shellscript",
			"text/plain",
			"text/x-shellscript",
		},
		Analyse: &chroma.AnalyseConfig{
			Regexes: []chroma.RegexConfig{
				{
					Pattern: "(?m)^#!.*/bin/(?:env(?: -[a-zA-Z0-9]+)*(?: --[a-zA-Z0-9-=]+)* |)nu",
					Score:   1,
				},
			},
			First: true,
		},
	}},
	{"embedded/objective-c.xml", chroma.Config{
		Name: "Objective-C",
		Aliases: []string{
			"objective-c",
			"objectivec",
			"obj-c",
			"objc",
		},
		Filenames: []string{
			"*.m",
			"*.h",
		},
		MimeTypes: []string{
			"text/x-objective-c",
		},
	}},
	{"embedded/objectpascal.xml", chroma.Config{
		Name: "ObjectPascal",
		Aliases: []string{
			"objectpascal",
		},
		Filenames: []string{
			"*.pas",
			"*.pp",
			"*.inc",
			"*.dpr",
			"*.dpk",
			"*.lpr",
			"*.lpk",
		},
		MimeTypes: []string{
			"text/x-pascal",
		},
	}},
	{"embedded/ocaml.xml", chroma.Config{
		Name: "OCaml",
		Aliases: []string{
			"ocaml",
		},
		Filenames: []string{
			"*.ml",
			"*.mli",
			"*.mll",
			"*.mly",
		},
		MimeTypes: []string{
			"text/x-ocaml",
		},
	}},
	{"embedded/octave.xml", chroma.Config{
		Name: "Octave",
		Aliases: []string{
			"octave",
		},
		Filenames: []string{
			"*.m",
		},
		MimeTypes: []string{
			"text/octave",
		},
	}},
	{"embedded/odin.xml", chroma.Config{
		Name: "Odin",
		Aliases: []string{
			"odin",
		},
		Filenames: []string{
			"*.odin",
		},
		MimeTypes: []string{
			"text/odin",
		},
	}},
	{"embedded/onesenterprise.xml", chroma.Config{
		Name: "OnesEnterprise",
		Aliases: []string{
			"ones",
			"onesenterprise",
			"1S",
			"1S:Enterprise",
		},
		Filenames: []string{
			"*.EPF",
			"*.epf",
			"*.ERF",
			"*.erf",
		},
		MimeTypes: []string{
			"application/octet-stream",
		},
		CaseInsensitive: true,
	}},
	{"embedded/openedge_abl.xml", chroma.Config{
		Name: "OpenEdge ABL",
		Aliases: []string{
			"openedge",
			"abl",
			"progress",
			"openedgeabl",
		},
		Filenames: []string{
			"*.p",
			"*.cls",
			"*.w",
			"*.i",
		},
		MimeTypes: []string{
			"text/x-openedge",
			"application/x-openedge",
		},
	}},
	{"embedded/openscad.xml", chroma.Config{
		Name: "OpenSCAD",
		Aliases: []string{
			"openscad",
		},
		Filenames: []string{
			"*.scad",
		},
		MimeTypes: []string{
			"text/x-scad",
		},
	}},
	{"embedded/org_mode.xml", chroma.Config{
		Name: "Org Mode",
		Aliases: []string{
			"org",
			"orgmode",
		},
		Filenames: []string{
			"*.org",
		},
		MimeTypes: []string{
			"text/org",
		},
	}},
	{"embedded/pacmanconf.xml", chroma.Config{
		Name: "PacmanConf",
		Aliases: []string{
			"pacmanconf",
		},
		Filenames: []string{
			"pacman.conf",
		},
	}},
	{"embedded/perl.xml", chroma.Config{
		Name: "Perl",
		Aliases: []string{
			"perl",
			"pl",
		},
		Filenames: []string{
			"*.pl",
			"*.pm",
			"*.t",
		},
		MimeTypes: []string{
			"text/x-perl",
			"application/x-perl",
		},
		DotAll: true,
	}},
	{"embedded/php.xml", chroma.Config{
		Name: "PHP",
		Aliases: []string{
			"php",
			"php3",
			"php4",
			"php5",
		},
		Filenames: []string{
			"*.php",
			"*.php[345]",
			"*.inc",
		},
		MimeTypes: []string{
			"text/x-php",
		},
		CaseInsensitive: true,
		DotAll:          true,
		EnsureNL:        true,
		Priority:        3,
	}},
	{"embedded/pig.xml", chroma.Config{
		Name: "Pig",
		Aliases: []string{
			"pig",
		},
		Filenames: []string{
			"*.pig",
		},
		MimeTypes: []string{
			"text/x-pig",
		},
		CaseInsensitive: true,
	}},
	{"embedded/pkgconfig.xml", chroma.Config{
		Name: "PkgConfig",
		Aliases: []string{
			"pkgconfig",
		},
		Filenames: []string{
			"*.pc",
		},
	}},
	{"embedded/pl_pgsql.xml", chroma.Config{
		Name: "PL/pgSQL",
		Aliases: []string{
			"plpgsql",
		},
		MimeTypes: []string{
			"text/x-plpgsql",
		},
		CaseInsensitive: true,
		NotMultiline:    true,
	}},
	{"embedded/plaintext.xml", chroma.Config{
		Name: "plaintext",
		Aliases: []string{
			"text",
			"plain",
			"no-highlight",
		},
		Filenames: []string{
			"*.txt",
		},
		MimeTypes: []string{
			"text/plain",
		},
		Priority: -1,
	}},
	{"embedded/plan9rc.xml", chroma.Config{
		Name: "Plan 9 rc",
		Aliases: []string{
			"plan9rc",
			"rc",
		},
		Filenames: []string{
			"*.rc",
		},
		MimeTypes: []string{
			"text/x-plan9-rc",
		},
		EnsureNL: true,
		Analyse: &chroma.AnalyseConfig{
			Regexes: []chroma.RegexConfig{
				{
					Pattern: "(?m)^#!.*/bin/(?:env\\s+)?rc\\b",
					Score:   1,
				},
			},
			First: true,
		},
	}},
	{"embedded/plutus_core.xml", chroma.Config{
		Name: "Plutus Core",
		Aliases: []string{
			"plutus-core",
			"plc",
		},
		Filenames: []string{
			"*.plc",
		},
		MimeTypes: []string{
			"text/x-plutus-core",
			"application/x-plutus-core",
		},
	}},
	{"embedded/pony.xml", chroma.Config{
		Name: "Pony",
		Aliases: []string{
			"pony",
		},
		Filenames: []string{
			"*.pony",
		},
	}},
	{"embedded/postgresql_sql_dialect.xml", chroma.Config{
		Name: "PostgreSQL SQL dialect",
		Aliases: []string{
			"postgresql",
			"postgres",
		},
		MimeTypes: []string{
			"text/x-postgresql",
		},
		CaseInsensitive: true,
		NotMultiline:    true,
	}},
	{"embedded/postscript.xml", chroma.Config{
		Name: "PostScript",
		Aliases: []string{
			"postscript",
			"postscr",
		},
		Filenames: []string{
			"*.ps",
			"*.eps",
			"*.epsf",
			"*.epsi",
			"*.pfa",
			"*.t42",
		},
		MimeTypes: []string{
			"application/postscript",
		},
	}},
	{"embedded/povray.xml", chroma.Config{
		Name: "POVRay",
		Aliases: []string{
			"pov",
		},
		Filenames: []string{
			"*.pov",
			"*.inc",
		},
		MimeTypes: []string{
			"text/x-povray",
		},
	}},
	{"embedded/powerquery.xml", chroma.Config{
		Name: "PowerQuery",
		Aliases: []string{
			"powerquery",
			"pq",
		},
		Filenames: []string{
			"*.pq",
		},
		MimeTypes: []string{
			"text/x-powerquery",
		},
		CaseInsensitive: true,
		DotAll:          true,
	}},
	{"embedded/powershell.xml", chroma.Config{
		Name: "PowerShell",
		Aliases: []string{
			"powershell",
			"posh",
			"ps1",
			"psm1",
			"psd1",
			"pwsh",
		},
		Filenames: []string{
			"*.ps1",
			"*.psm1",
			"*.psd1",
		},
		MimeTypes: []string{
			"text/x-powershell",
		},
		CaseInsensitive: true,
		DotAll:          true,
	}},
	{"embedded/prolog.xml", chroma.Config{
		Name: "Prolog",
		Aliases: []string{
			"prolog",
		},
		Filenames: []string{
			"*.ecl",
			"*.prolog",
			"*.pro",
			"*.pl",
		},
		MimeTypes: []string{
			"text/x-prolog",
		},
	}},
	{"embedded/promela.xml", chroma.Config{
		Name: "Promela",
		Aliases: []string{
			"promela",
		},
		Filenames: []string{
			"*.pml",
			"*.prom",
			"*.prm",
			"*.promela",
			"*.pr",
			"*.pm",
		},
		MimeTypes: []string{
			"text/x-promela",
		},
	}},
	{"embedded/promql.xml", chroma.Config{
		Name: "PromQL",
		Aliases: []string{
			"promql",
		},
		Filenames: []string{
			"*.promql",
		},
	}},
	{"embedded/properties.xml", chroma.Config{
		Name: "properties",
		Aliases: []string{
			"java-properties",
		},
		Filenames: []string{
			"*.properties",
		},
		MimeTypes: []string{
			"text/x-java-properties",
		},
	}},
	{"embedded/protocol_buffer.xml", chroma.Config{
		Name: "Protocol Buffer",
		Aliases: []string{
			"protobuf",
			"proto",
		},
		Filenames: []string{
			"*.proto",
		},
	}},
	{"embedded/prql.xml", chroma.Config{
		Name: "PRQL",
		Aliases: []string{
			"prql",
		},
		Filenames: []string{
			"*.prql",
		},
		MimeTypes: []string{
			"application/prql",
		},
	}},
	{"embedded/psl.xml", chroma.Config{
		Name: "PSL",
		Aliases: []string{
			"psl",
		},
		Filenames: []string{
			"*.psl",
			"*.BATCH",
			"*.TRIG",
			"*.PROC",
		},
		MimeTypes: []string{
			"text/x-psl",
		},
	}},
	{"embedded/puppet.xml", chroma.Config{
		Name: "Puppet",
		Aliases: []string{
			"puppet",
		},
		Filenames: []string{
			"*.pp",
		},
	}},
	{"embedded/python.xml", chroma.Config{
		Name: "Python",
		Aliases: []string{
			"python",
			"py",
			"sage",
			"python3",
			"py3",
			"starlark",
		},
		Filenames: []string{
			"*.py",
			"*.pyi",
			"*.pyw",
			"*.jy",
			"*.sage",
			"*.sc",
			"SConstruct",
			"SConscript",
			"*.bzl",
			"BUCK",
			"BUILD",
			"BUILD.bazel",
			"WORKSPACE",
			"WORKSPACE.bzlmod",
			"WORKSPACE.bazel",
			"MODULE.bazel",
			"REPO.bazel",
			"*.star",
			"*.tac",
		},
		MimeTypes: []string{
			"text/x-python",
			"application/x-python",
			"text/x-python3",
			"application/x-python3",
		},
	}},
	{"embedded/python_2.xml", chroma.Config{
		Name: "Python 2",
		Aliases: []string{
			"python2",
			"py2",
		},
		MimeTypes: []string{
			"text/x-python2",
			"application/x-python2",
		},
	}},
	{"embedded/qbasic.xml", chroma.Config{
		Name: "QBasic",
		Aliases: []string{
			"qbasic",
			"basic",
		},
		Filenames: []string{
			"*.BAS",
			"*.bas",
		},
		MimeTypes: []string{
			"text/basic",
		},
	}},
	{"embedded/qml.xml", chroma.Config{
		Name: "QML",
		Aliases: []string{
			"qml",
			"qbs",
		},
		Filenames: []string{
			"*.qml",
			"*.qbs",
		},
		MimeTypes: []string{
			"application/x-qml",
			"application/x-qt.qbs+qml",
		},
		DotAll: true,
	}},
	{"embedded/r.xml", chroma.Config{
		Name: "R",
		Aliases: []string{
			"splus",
			"s",
			"r",
		},
		Filenames: []string{
			"*.S",
			"*.R",
			"*.r",
			".Rhistory",
			".Rprofile",
			".Renviron",
		},
		MimeTypes: []string{
			"text/S-plus",
			"text/S",
			"text/x-r-source",
			"text/x-r",
			"text/x-R",
			"text/x-r-history",
			"text/x-r-profile",
		},
		Priority: 0.1,
	}},
	{"embedded/racket.xml", chroma.Config{
		Name: "Racket",
		Aliases: []string{
			"racket",
			"rkt",
		},
		Filenames: []string{
			"*.rkt",
			"*.rktd",
			"*.rktl",
		},
		MimeTypes: []string{
			"text/x-racket",
			"application/x-racket",
		},
	}},
	{"embedded/ragel.xml", chroma.Config{
		Name: "Ragel",
		Aliases: []string{
			"ragel",
		},
	}},
	{"embedded/react.xml", chroma.Config{
		Name: "react",
		Aliases: []string{
			"jsx",
			"react",
		},
		Filenames: []string{
			"*.jsx",
			"*.react",
		},
		MimeTypes: []string{
			"text/jsx",
			"text/typescript-jsx",
		},
		DotAll: true,
	}},
	{"embedded/reasonml.xml", chroma.Config{
		Name: "ReasonML",
		Aliases: []string{
			"reason",
			"reasonml",
		},
		Filenames: []string{
			"*.re",
			"*.rei",
		},
		MimeTypes: []string{
			"text/x-reasonml",
		},
	}},
	{"embedded/reg.xml", chroma.Config{
		Name: "reg",
		Aliases: []string{
			"registry",
		},
		Filenames: []string{
			"*.reg",
		},
		MimeTypes: []string{
			"text/x-windows-registry",
		},
	}},
	{"embedded/rego.xml", chroma.Config{
		Name: "Rego",
		Aliases: []string{
			"rego",
		},
		Filenames: []string{
			"*.rego",
		},
	}},
	{"embedded/rexx.xml", chroma.Config{
		Name: "Rexx",
		Aliases: []string{
			"rexx",
			"arexx",
		},
		Filenames: []string{
			"*.rexx",
			"*.rex",
			"*.rx",
			"*.arexx",
		},
		MimeTypes: []string{
			"text/x-rexx",
		},
		CaseInsensitive: true,
		NotMultiline:    true,
	}},
	{"embedded/rgbasm.xml", chroma.Config{
		Name: "RGBDS Assembly",
		Aliases: []string{
			"rgbasm",
		},
		Filenames: []string{
			"*.asm",
		},
		CaseInsensitive: true,
		Priority:        0.5,
	}},
	{"embedded/ring.xml", chroma.Config{
		Name: "Ring",
		Aliases: []string{
			"ring",
		},
		Filenames: []string{
			"*.ring",
			"*.rh",
			"*.rform",
		},
		MimeTypes: []string{
			"text/x-ring",
		},
		CaseInsensitive: true,
	}},
	{"embedded/rpgle.xml", chroma.Config{
		Name: "RPGLE",
		Aliases: []string{
			"SQLRPGLE",
			"RPG IV",
		},
		Filenames: []string{
			"*.RPGLE",
			"*.rpgle",
			"*.SQLRPGLE",
			"*.sqlrpgle",
		},
		MimeTypes: []string{
			"text/x-rpgle",
			"text/x-sqlrpgle",
		},
		CaseInsensitive: true,
		Analyse: &chroma.AnalyseConfig{
			Regexes: []chroma.RegexConfig{
				{
					Pattern: "\\*\\*free",
					Score:   0.9,
				},
				{
					Pattern: "ctl-opt",
					Score:   0.9,
				},
				{
					Pattern: "dcl-(ds|s|f|proc|pr|pi)",
					Score:   0.9,
				},
				{
					Pattern: "\\*in[0-9][0-9]",
					Score:   0.5,
				},
			},
		},
	}},
	{"embedded/rpm_spec.xml", chroma.Config{
		Name: "RPMSpec",
		Aliases: []string{
			"spec",
		},
		Filenames: []string{
			"*.spec",
		},
		MimeTypes: []string{
			"text/x-rpm-spec",
		},
	}},
	{"embedded/ruby.xml", chroma.Config{
		Name: "Ruby",
		Aliases: []string{
			"rb",
			"ruby",
			"duby",
		},
		Filenames: []string{
			"*.rb",
			"*.rbw",
			"Rakefile",
			"*.rake",
			"*.gemspec",
			"*.rbx",
			"*.duby",
			"Gemfile",
			"*.gemfile",
			"Vagrantfile",
			"Appraisals",
			".pryrc",
			"*.json.jbuilder",
		},
		MimeTypes: []string{
			"text/x-ruby",
			"application/x-ruby",
		},
		DotAll: true,
	}},
	{"embedded/rust.xml", chroma.Config{
		Name: "Rust",
		Aliases: []string{
			"rust",
			"rs",
		},
		Filenames: []string{
			"*.rs",
			"*.rs.in",
		},
		MimeTypes: []string{
			"text/rust",
			"text/x-rust",
		},
		EnsureNL: true,
	}},
	{"embedded/sas.xml", chroma.Config{
		Name: "SAS",
		Aliases: []string{
			"sas",
		},
		Filenames: []string{
			"*.SAS",
			"*.sas",
		},
		MimeTypes: []string{
			"text/x-sas",
			"text/sas",
			"application/x-sas",
		},
		CaseInsensitive: true,
	}},
	{"embedded/sass.xml", chroma.Config{
		Name: "Sass",
		Aliases: []string{
			"sass",
		},
		Filenames: []string{
			"*.sass",
		},
		MimeTypes: []string{
			"text/x-sass",
		},
		CaseInsensitive: true,
	}},
	{"embedded/scala.xml", chroma.Config{
		Name: "Scala",
		Aliases: []string{
			"scala",
		},
		Filenames: []string{
			"*.scala",
		},
		MimeTypes: []string{
			"text/x-scala",
		},
		DotAll: true,
	}},
	{"embedded/scdoc.xml", chroma.Config{
		Name: "scdoc",
		Aliases: []string{
			"scdoc",
		},
		Filenames: []string{
			"*.scd",
			"*.scdoc",
		},
	}},
	{"embedded/scheme.xml", chroma.Config{
		Name: "Scheme",
		Aliases: []string{
			"scheme",
			"scm",
		},
		Filenames: []string{
			"*.scm",
			"*.ss",
		},
		MimeTypes: []string{
			"text/x-scheme",
			"application/x-scheme",
		},
	}},
	{"embedded/scilab.xml", chroma.Config{
		Name: "Scilab",
		Aliases: []string{
			"scilab",
		},
		Filenames: []string{
			"*.sci",
			"*.sce",
			"*.tst",
		},
		MimeTypes: []string{
			"text/scilab",
		},
	}},
	{"embedded/scss.xml", chroma.Config{
		Name: "SCSS",
		Aliases: []string{
			"scss",
		},
		Filenames: []string{
			"*.scss",
		},
		MimeTypes: []string{
			"text/x-scss",
		},
		CaseInsensitive: true,
		DotAll:          true,
		NotMultiline:    true,
	}},
	{"embedded/sed.xml", chroma.Config{
		Name: "Sed",
		Aliases: []string{
			"sed",
			"gsed",
			"ssed",
		},
		Filenames: []string{
			"*.sed",
			"*.[gs]sed",
		},
		MimeTypes: []string{
			"text/x-sed",
		},
	}},
	{"embedded/sieve.xml", chroma.Config{
		Name: "Sieve",
		Aliases: []string{
			"sieve",
		},
		Filenames: []string{
			"*.siv",
			"*.sieve",
		},
	}},
	{"embedded/smali.xml", chroma.Config{
		Name: "Smali",
		Aliases: []string{
			"smali",
		},
		Filenames: []string{
			"*.smali",
		},
		MimeTypes: []string{
			"text/smali",
		},
	}},
	{"embedded/smalltalk.xml", chroma.Config{
		Name: "Smalltalk",
		Aliases: []string{
			"smalltalk",
			"squeak",
			"st",
		},
		Filenames: []string{
			"*.st",
		},
		MimeTypes: []string{
			"text/x-smalltalk",
		},
	}},
	{"embedded/smarty.xml", chroma.Config{
		Name: "Smarty",
		Aliases: []string{
			"smarty",
		},
		Filenames: []string{
			"*.tpl",
		},
		MimeTypes: []string{
			"application/x-smarty",
		},
		DotAll: true,
	}},
	{"embedded/snbt.xml", chroma.Config{
		Name: "SNBT",
		Aliases: []string{
			"snbt",
		},
		Filenames: []string{
			"*.snbt",
		},
		MimeTypes: []string{
			"text/snbt",
		},
	}},
	{"embedded/snobol.xml", chroma.Config{
		Name: "Snobol",
		Aliases: []string{
			"snobol",
		},
		Filenames: []string{
			"*.snobol",
		},
		MimeTypes: []string{
			"text/x-snobol",
		},
	}},
	{"embedded/solidity.xml", chroma.Config{
		Name: "Solidity",
		Aliases: []string{
			"sol",
			"solidity",
		},
		Filenames: []string{
			"*.sol",
		},
		DotAll: true,
	}},
	{"embedded/sourcepawn.xml", chroma.Config{
		Name: "SourcePawn",
		Aliases: []string{
			"sp",
		},
		Filenames: []string{
			"*.sp",
			"*.inc",
		},
		MimeTypes: []string{
			"text/x-sourcepawn",
		},
	}},
	{"embedded/spade.xml", chroma.Config{
		Name: "Spade",
		Aliases: []string{
			"spade",
		},
		Filenames: []string{
			"*.spade",
		},
		MimeTypes: []string{
			"text/spade",
			"text/x-spade",
		},
		EnsureNL: true,
	}},
	{"embedded/sparql.xml", chroma.Config{
		Name: "SPARQL",
		Aliases: []string{
			"sparql",
		},
		Filenames: []string{
			"*.rq",
			"*.sparql",
		},
		MimeTypes: []string{
			"application/sparql-query",
		},
	}},
	{"embedded/sql.xml", chroma.Config{
		Name: "SQL",
		Aliases: []string{
			"sql",
		},
		Filenames: []string{
			"*.sql",
		},
		MimeTypes: []string{
			"text/x-sql",
		},
		CaseInsensitive: true,
		NotMultiline:    true,
	}},
	{"embedded/squidconf.xml", chroma.Config{
		Name: "SquidConf",
		Aliases: []string{
			"squidconf",
			"squid.conf",
			"squid",
		},
		Filenames: []string{
			"squid.conf",
		},
		MimeTypes: []string{
			"text/x-squidconf",
		},
		CaseInsensitive: true,
		NotMultiline:    true,
	}},
	{"embedded/ssh_config.xml", chroma.Config{
		Name: "SSH config",
		Aliases: []string{
			"sshconfig",
			"ssh-config",
			"ssh_config",
		},
		Filenames: []string{
			"ssh_config",
		},
		MimeTypes: []string{
			"text/x-ssh-config",
		},
		CaseInsensitive: true,
	}},
	{"embedded/standard_ml.xml", chroma.Config{
		Name: "Standard ML",
		Aliases: []string{
			"sml",
		},
		Filenames: []string{
			"*.sml",
			"*.sig",
			"*.fun",
		},
		MimeTypes: []string{
			"text/x-standardml",
			"application/x-standardml",
		},
	}},
	{"embedded/stas.xml", chroma.Config{
		Name: "stas",
		Filenames: []string{
			"*.stas",
		},
	}},
	{"embedded/stylus.xml", chroma.Config{
		Name: "Stylus",
		Aliases: []string{
			"stylus",
		},
		Filenames: []string{
			"*.styl",
		},
		MimeTypes: []string{
			"text/x-styl",
		},
		CaseInsensitive: true,
	}},
	{"embedded/swift.xml", chroma.Config{
		Name: "Swift",
		Aliases: []string{
			"swift",
		},
		Filenames: []string{
			"*.swift",
		},
		MimeTypes: []string{
			"text/x-swift",
		},
	}},
	{"embedded/systemd.xml", chroma.Config{
		Name: "SYSTEMD",
		Aliases: []string{
			"systemd",
		},
		Filenames: []string{
			"*.automount",
			"*.device",
			"*.dnssd",
			"*.link",
			"*.mount",
			"*.netdev",
			"*.network",
			"*.path",
			"*.scope",
			"*.service",
			"*.slice",
			"*.socket",
			"*.swap",
			"*.target",
			"*.timer",
		},
		MimeTypes: []string{
			"text/plain",
		},
	}},
	{"embedded/systemverilog.xml", chroma.Config{
		Name: "systemverilog",
		Aliases: []string{
			"systemverilog",
			"sv",
		},
		Filenames: []string{
			"*.sv",
			"*.svh",
		},
		MimeTypes: []string{
			"text/x-systemverilog",
		},
		EnsureNL: true,
	}},
	{"embedded/tablegen.xml", chroma.Config{
		Name: "TableGen",
		Aliases: []string{
			"tablegen",
		},
		Filenames: []string{
			"*.td",
		},
		MimeTypes: []string{
			"text/x-tablegen",
		},
	}},
	{"embedded/tal.xml", chroma.Config{
		Name: "Tal",
		Aliases: []string{
			"tal",
			"uxntal",
		},
		Filenames: []string{
			"*.tal",
		},
		MimeTypes: []string{
			"text/x-uxntal",
		},
	}},
	{"embedded/tasm.xml", chroma.Config{
		Name: "TASM",
		Aliases: []string{
			"tasm",
		},
		Filenames: []string{
			"*.asm",
			"*.ASM",
			"*.tasm",
		},
		MimeTypes: []string{
			"text/x-tasm",
		},
		CaseInsensitive: true,
	}},
	{"embedded/tcl.xml", chroma.Config{
		Name: "Tcl",
		Aliases: []string{
			"tcl",
		},
		Filenames: []string{
			"*.tcl",
			"*.rvt",
		},
		MimeTypes: []string{
			"text/x-tcl",
			"text/x-script.tcl",
			"application/x-tcl",
		},
	}},
	{"embedded/tcsh.xml", chroma.Config{
		Name: "Tcsh",
		Aliases: []string{
			"tcsh",
			"csh",
		},
		Filenames: []string{
			"*.tcsh",
			"*.csh",
		},
		MimeTypes: []string{
			"application/x-csh",
		},
	}},
	{"embedded/templ.xml", chroma.Config{
		Name: "Templ",
		Aliases: []string{
			"templ",
		},
		Filenames: []string{
			"*.templ",
		},
		MimeTypes: []string{
			"text/x-templ",
		},
		DotAll: true,
		Analyse: &chroma.AnalyseConfig{
			Regexes: []chroma.RegexConfig{
				{
					Pattern: "(?m)^\\s*templ\\s+[A-Za-z_]\\w*\\s*\\(",
					Score:   0.7,
				},
				{
					Pattern: "(?m)^\\s*package\\s+\\w+[\\s\\S]*^\\s*templ\\s+",
					Score:   0.5,
				},
			},
		},
	}},
	{"embedded/termcap.xml", chroma.Config{
		Name: "Termcap",
		Aliases: []string{
			"termcap",
		},
		Filenames: []string{
			"termcap",
			"termcap.src",
		},
	}},
	{"embedded/terminfo.xml", chroma.Config{
		Name: "Terminfo",
		Aliases: []string{
			"terminfo",
		},
		Filenames: []string{
			"terminfo",
			"terminfo.src",
		},
	}},
	{"embedded/terraform.xml", chroma.Config{
		Name: "Terraform",
		Aliases: []string{
			"terraform",
			"tf",
			"hcl",
		},
		Filenames: []string{
			"*.tf",
			"*.hcl",
		},
		MimeTypes: []string{
			"application/x-tf",
			"application/x-terraform",
		},
	}},
	{"embedded/tex.xml", chroma.Config{
		Name: "TeX",
		Aliases: []string{
			"tex",
			"latex",
		},
		Filenames: []string{
			"*.tex",
			"*.aux",
			"*.toc",
		},
		MimeTypes: []string{
			"text/x-tex",
			"text/x-latex",
		},
	}},
	{"embedded/thrift.xml", chroma.Config{
		Name: "Thrift",
		Aliases: []string{
			"thrift",
		},
		Filenames: []string{
			"*.thrift",
		},
		MimeTypes: []string{
			"application/x-thrift",
		},
	}},
	{"embedded/toml.xml", chroma.Config{
		Name: "TOML",
		Aliases: []string{
			"toml",
		},
		Filenames: []string{
			"*.toml",
			"Pipfile",
			"poetry.lock",
			"uv.lock",
		},
		MimeTypes: []string{
			"text/x-toml",
		},
	}},
	{"embedded/tradingview.xml", chroma.Config{
		Name: "TradingView",
		Aliases: []string{
			"tradingview",
			"tv",
		},
		Filenames: []string{
			"*.tv",
		},
		MimeTypes: []string{
			"text/x-tradingview",
		},
		DotAll:   true,
		EnsureNL: true,
	}},
	{"embedded/transact-sql.xml", chroma.Config{
		Name: "Transact-SQL",
		Aliases: []string{
			"tsql",
			"t-sql",
		},
		MimeTypes: []string{
			"text/x-tsql",
		},
		CaseInsensitive: true,
		NotMultiline:    true,
	}},
	{"embedded/turing.xml", chroma.Config{
		Name: "Turing",
		Aliases: []string{
			"turing",
		},
		Filenames: []string{
			"*.turing",
			"*.tu",
		},
		MimeTypes: []string{
			"text/x-turing",
		},
	}},
	{"embedded/turtle.xml", chroma.Config{
		Name: "Turtle",
		Aliases: []string{
			"turtle",
		},
		Filenames: []string{
			"*.ttl",
		},
		MimeTypes: []string{
			"text/turtle",
			"application/x-turtle",
		},
		CaseInsensitive: true,
		NotMultiline:    true,
	}},
	{"embedded/twig.xml", chroma.Config{
		Name: "Twig",
		Aliases: []string{
			"twig",
		},
		Filenames: []string{
			"*.twig",
		},
		MimeTypes: []string{
			"application/x-twig",
		},
		DotAll: true,
	}},
	{"embedded/txtpb.xml", chroma.Config{
		Name: "Protocol Buffer Text Format",
		Aliases: []string{
			"txtpb",
		},
		Filenames: []string{
			"*.txtpb",
			"*.textproto",
			"*.textpb",
			"*.pbtxt",
		},
		MimeTypes: []string{
			"application/x-protobuf-text",
		},
		EnsureNL: true,
	}},
	{"embedded/typescript.xml", chroma.Config{
		Name: "TypeScript",
		Aliases: []string{
			"ts",
			"tsx",
			"typescript",
		},
		Filenames: []string{
			"*.ts",
			"*.tsx",
			"*.mts",
			"*.cts",
		},
		MimeTypes: []string{
			"text/x-typescript",
		},
		DotAll:   true,
		EnsureNL: true,
	}},
	{"embedded/typoscript.xml", chroma.Config{
		Name: "TypoScript",
		Aliases: []string{
			"typoscript",
		},
		Filenames: []string{
			"*.ts",
		},
		MimeTypes: []string{
			"text/x-typoscript",
		},
		DotAll:   true,
		Priority: 0.1,
	}},
	{"embedded/typoscriptcssdata.xml", chroma.Config{
		Name: "TypoScriptCssData",
		Aliases: []string{
			"typoscriptcssdata",
		},
	}},
	{"embedded/typoscripthtmldata.xml", chroma.Config{
		Name: "TypoScriptHtmlData",
		Aliases: []string{
			"typoscripthtmldata",
		},
	}},
	{"embedded/typst.xml", chroma.Config{
		Name: "Typst",
		Aliases: []string{
			"typst",
		},
		Filenames: []string{
			"*.typ",
		},
		MimeTypes: []string{
			"text/x-typst",
		},
	}},
	{"embedded/ucode.xml", chroma.Config{
		Name: "ucode",
		Filenames: []string{
			"*.uc",
		},
		MimeTypes: []string{
			"application/x.ucode",
			"text/x.ucode",
		},
		DotAll:   true,
		EnsureNL: true,
	}},
	{"embedded/v.xml", chroma.Config{
		Name: "V",
		Aliases: []string{
			"v",
			"vlang",
		},
		Filenames: []string{
			"*.v",
			"*.vv",
			"v.mod",
		},
		MimeTypes: []string{
			"text/x-v",
		},
		EnsureNL: true,
	}},
	{"embedded/v_shell.xml", chroma.Config{
		Name: "V shell",
		Aliases: []string{
			"vsh",
			"vshell",
		},
		Filenames: []string{
			"*.vsh",
		},
		MimeTypes: []string{
			"text/x-vsh",
		},
		EnsureNL: true,
	}},
	{"embedded/vala.xml", chroma.Config{
		Name: "Vala",
		Aliases: []string{
			"vala",
			"vapi",
		},
		Filenames: []string{
			"*.vala",
			"*.vapi",
		},
		MimeTypes: []string{
			"text/x-vala",
		},
	}},
	{"embedded/vb_net.xml", chroma.Config{
		Name: "VB.net",
		Aliases: []string{
			"vb.net",
			"vbnet",
		},
		Filenames: []string{
			"*.vb",
			"*.bas",
		},
		MimeTypes: []string{
			"text/x-vbnet",
			"text/x-vba",
		},
		CaseInsensitive: true,
	}},
	{"embedded/verilog.xml", chroma.Config{
		Name: "verilog",
		Aliases: []string{
			"verilog",
			"v",
		},
		Filenames: []string{
			"*.v",
		},
		MimeTypes: []string{
			"text/x-verilog",
		},
		EnsureNL: true,
	}},
	{"embedded/vhdl.xml", chroma.Config{
		Name: "VHDL",
		Aliases: []string{
			"vhdl",
		},
		Filenames: []string{
			"*.vhdl",
			"*.vhd",
		},
		MimeTypes: []string{
			"text/x-vhdl",
		},
		CaseInsensitive: true,
	}},
	{"embedded/vhs.xml", chroma.Config{
		Name: "VHS",
		Aliases: []string{
			"vhs",
			"tape",
			"cassette",
		},
		Filenames: []string{
			"*.tape",
		},
	}},
	{"embedded/viml.xml", chroma.Config{
		Name: "VimL",
		Aliases: []string{
			"vim",
		},
		Filenames: []string{
			"*.vim",
			".vimrc",
			".exrc",
			".gvimrc",
			"_vimrc",
			"_exrc",
			"_gvimrc",
			"vimrc",
			"gvimrc",
		},
		MimeTypes: []string{
			"text/x-vim",
		},
	}},
	{"embedded/vue.xml", chroma.Config{
		Name: "vue",
		Aliases: []string{
			"vue",
			"vuejs",
		},
		Filenames: []string{
			"*.vue",
		},
		MimeTypes: []string{
			"text/x-vue",
			"application/x-vue",
		},
		DotAll: true,
	}},
	{"embedded/wat.xml", chroma.Config{
		Name: "WebAssembly Text Format",
		Aliases: []string{
			"wast",
			"wat",
		},
		Filenames: []string{
			"*.wat",
			"*.wast",
		},
	}},
	{"embedded/wdte.xml", chroma.Config{
		Name: "WDTE",
		Filenames: []string{
			"*.wdte",
		},
	}},
	{"embedded/webgpu_shading_language.xml", chroma.Config{
		Name: "WebGPU Shading Language",
		Aliases: []string{
			"wgsl",
		},
		Filenames: []string{
			"*.wgsl",
		},
		MimeTypes: []string{
			"text/wgsl",
		},
	}},
	{"embedded/webvtt.xml", chroma.Config{
		Name: "WebVTT",
		Aliases: []string{
			"vtt",
		},
		Filenames: []string{
			"*.vtt",
		},
		MimeTypes: []string{
			"text/vtt",
		},
	}},
	{"embedded/whiley.xml", chroma.Config{
		Name: "Whiley",
		Aliases: []string{
			"whiley",
		},
		Filenames: []string{
			"*.whiley",
		},
		MimeTypes: []string{
			"text/x-whiley",
		},
	}},
	{"embedded/xml.xml", chroma.Config{
		Name: "XML",
		Aliases: []string{
			"xml",
		},
		Filenames: []string{
			"*.xml",
			"*.xsl",
			"*.rss",
			"*.xslt",
			"*.xsd",
			"*.wsdl",
			"*.wsf",
			"*.svg",
			"*.qrc",
			"*.csproj",
			"*.vcxproj",
			"*.fsproj",
		},
		MimeTypes: []string{
			"text/xml",
			"application/xml",
			"image/svg+xml",
			"application/rss+xml",
			"application/atom+xml",
		},
		DotAll: true,
	}},
	{"embedded/xorg.xml", chroma.Config{
		Name: "Xorg",
		Aliases: []string{
			"xorg.conf",
		},
		Filenames: []string{
			"xorg.conf",
		},
	}},
	{"embedded/yaml.xml", chroma.Config{
		Name: "YAML",
		Aliases: []string{
			"yaml",
		},
		Filenames: []string{
			"*.yaml",
			"*.yml",
		},
		MimeTypes: []string{
			"text/x-yaml",
		},
	}},
	{"embedded/yang.xml", chroma.Config{
		Name: "YANG",
		Aliases: []string{
			"yang",
		},
		Filenames: []string{
			"*.yang",
		},
		MimeTypes: []string{
			"application/yang",
		},
	}},
	{"embedded/z80_assembly.xml", chroma.Config{
		Name: "Z80 Assembly",
		Aliases: []string{
			"z80",
		},
		Filenames: []string{
			"*.z80",
			"*.asm",
		},
		CaseInsensitive: true,
	}},
	{"embedded/zed.xml", chroma.Config{
		Name: "Zed",
		Aliases: []string{
			"zed",
		},
		Filenames: []string{
			"*.zed",
		},
		MimeTypes: []string{
			"text/zed",
		},
	}},
	{"embedded/zig.xml", chroma.Config{
		Name: "Zig",
		Aliases: []string{
			"zig",
		},
		Filenames: []string{
			"*.zig",
			"*.zon",
		},
		MimeTypes: []string{
			"text/zig",
		},
	}},
}
