// Command metadatagen generates a Go source file containing the <config>
// section of every embedded lexer XML definition, so that the lexer registry
// can be constructed without parsing any XML at init time.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"io/fs"
	"log"
	"os"

	"github.com/alecthomas/chroma/v3"
	"github.com/alecthomas/repr"
	"github.com/dlclark/regexp2/v2"
)

func main() {
	log.SetFlags(0)
	log.SetPrefix("metadatagen: ")
	dir := flag.String("dir", "embedded", "directory containing lexer XML definitions")
	out := flag.String("out", "lexers_gen.go", "output file")
	flag.Parse()

	fsys := os.DirFS(*dir)
	paths, err := fs.Glob(fsys, "*.xml")
	if err != nil {
		log.Fatal(err)
	}

	buf := &bytes.Buffer{}
	fmt.Fprintf(buf, `// Code generated by "go generate" (internal/metadatagen); DO NOT EDIT.

package lexers

import (
	"github.com/alecthomas/chroma/v3"
)

// embeddedLexers mirrors the <config> element of every XML lexer definition
// under embedded/, so that the registry can be built without parsing XML at
// init time. TestEmbeddedLexerMetadata verifies it is up to date.
var embeddedLexers = []struct {
	path   string
	config chroma.Config
}{
`)
	for _, path := range paths {
		lexer, err := chroma.NewXMLLexer(fsys, path)
		if err != nil {
			log.Fatalf("%s: %s", path, err)
		}
		config := lexer.Config()
		validateAnalysers(path, config)
		fmt.Fprintf(buf, "\t{%q, %s},\n", "embedded/"+path, repr.String(*config, repr.Indent("\t")))
	}
	fmt.Fprintf(buf, "}\n")

	source, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("formatting generated source: %s", err)
	}
	if err := os.WriteFile(*out, source, 0o600); err != nil {
		log.Fatal(err)
	}
}

// validateAnalysers compiles the analyser regexes so that an invalid pattern
// fails at generation time; at runtime they are compiled lazily.
func validateAnalysers(path string, config *chroma.Config) {
	if config.Analyse == nil {
		return
	}
	flags := regexp2.None
	if config.CaseInsensitive {
		flags = regexp2.IgnoreCase
	}
	for _, ra := range config.Analyse.Regexes {
		if _, err := regexp2.Compile(ra.Pattern, flags); err != nil {
			log.Fatalf("%s: %q is not a valid analyser regex: %s", path, ra.Pattern, err)
		}
	}
}
