package styles

import (
	"github.com/alecthomas/chroma"
)

// DraculaHighContrast Style
var DraculaHighContrast = Register(chroma.MustNewStyle("dracula-hc", chroma.StyleEntries{
	chroma.Comment:                  "#AAB8EB",
	chroma.CommentHashbang:          "#AAB8EB",
	chroma.CommentMultiline:         "#AAB8EB",
	chroma.CommentPreproc:           "#FF96D0",
	chroma.CommentSingle:            "#AAB8EB",
	chroma.CommentSpecial:           "#AAB8EB",
	chroma.Generic:                  "#f8f8f2",
	chroma.GenericDeleted:           "#FF9F9F",
	chroma.GenericEmph:              "#f8f8f2 underline",
	chroma.GenericError:             "#f8f8f2",
	chroma.GenericHeading:           "#f8f8f2 bold",
	chroma.GenericInserted:          "#f8f8f2 bold",
	chroma.GenericOutput:            "#B8BACD",
	chroma.GenericPrompt:            "#f8f8f2",
	chroma.GenericStrong:            "#f8f8f2",
	chroma.GenericSubheading:        "#f8f8f2 bold",
	chroma.GenericTraceback:         "#f8f8f2",
	chroma.GenericUnderline:         "underline",
	chroma.Error:                    "#f8f8f2",
	chroma.Keyword:                  "#FF96D0",
	chroma.KeywordConstant:          "#FF96D0",
	chroma.KeywordDeclaration:       "#8be9fd italic",
	chroma.KeywordNamespace:         "#FF96D0",
	chroma.KeywordPseudo:            "#FF96D0",
	chroma.KeywordReserved:          "#FF96D0",
	chroma.KeywordType:              "#8be9fd",
	chroma.Literal:                  "#f8f8f2",
	chroma.LiteralDate:              "#f8f8f2",
	chroma.Name:                     "#f8f8f2",
	chroma.NameAttribute:            "#50fa7b",
	chroma.NameBuiltin:              "#8be9fd italic",
	chroma.NameBuiltinPseudo:        "#f8f8f2",
	chroma.NameClass:                "#50fa7b",
	chroma.NameConstant:             "#f8f8f2",
	chroma.NameDecorator:            "#f8f8f2",
	chroma.NameEntity:               "#f8f8f2",
	chroma.NameException:            "#f8f8f2",
	chroma.NameFunction:             "#50fa7b",
	chroma.NameLabel:                "#8be9fd italic",
	chroma.NameNamespace:            "#f8f8f2",
	chroma.NameOther:                "#f8f8f2",
	chroma.NameTag:                  "#FF96D0",
	chroma.NameVariable:             "#8be9fd italic",
	chroma.NameVariableClass:        "#8be9fd italic",
	chroma.NameVariableGlobal:       "#8be9fd italic",
	chroma.NameVariableInstance:     "#8be9fd italic",
	chroma.LiteralNumber:            "#CAA7FF",
	chroma.LiteralNumberBin:         "#CAA7FF",
	chroma.LiteralNumberFloat:       "#CAA7FF",
	chroma.LiteralNumberHex:         "#CAA7FF",
	chroma.LiteralNumberInteger:     "#CAA7FF",
	chroma.LiteralNumberIntegerLong: "#CAA7FF",
	chroma.LiteralNumberOct:         "#CAA7FF",
	chroma.Operator:                 "#FF96D0",
	chroma.OperatorWord:             "#FF96D0",
	chroma.Other:                    "#f8f8f2",
	chroma.Punctuation:              "#f8f8f2",
	chroma.LiteralString:            "#f1fa8c",
	chroma.LiteralStringBacktick:    "#f1fa8c",
	chroma.LiteralStringChar:        "#f1fa8c",
	chroma.LiteralStringDoc:         "#f1fa8c",
	chroma.LiteralStringDouble:      "#f1fa8c",
	chroma.LiteralStringEscape:      "#f1fa8c",
	chroma.LiteralStringHeredoc:     "#f1fa8c",
	chroma.LiteralStringInterpol:    "#f1fa8c",
	chroma.LiteralStringOther:       "#f1fa8c",
	chroma.LiteralStringRegex:       "#f1fa8c",
	chroma.LiteralStringSingle:      "#f1fa8c",
	chroma.LiteralStringSymbol:      "#f1fa8c",
	chroma.Text:                     "#f8f8f2",
	chroma.TextWhitespace:           "#f8f8f2",
	chroma.Background:               " bg:#282a36",
}))
